#!/bin/bash

set -o pipefail
set -o nounset

PATH=${PATH}:../bin

LOGDIR=../logs
TSTAMP=$(date +%y%m%d.%H%M)
PWD=$(pwd)
IAM=$(basename ${PWD})
JOBNAME=${IAM}-
TSTAMP=$(date +%y%m%d.%H%M)

QSTATS_PARAMETERS="-V -c -b -B -P -R"
QSTATS_STDOUT_PARAMETERS="-D ${QSTATS_PARAMETERS}"

prepOut() {
  mkdir -p ${LOGDIR}/${TSTAMP}
  touch "${LOGDIR}/${TSTAMP}/${IAM}"
}

dumpStats() {
  logger -t ${IAM} -- "dump queue stats: begin"
  echo "Output: ${LOGDIR}/${TSTAMP}/${IAM}"
  qstats.sh ${QSTATS_STDOUT_PARAMETERS} | tee -a ${LOGDIR}/${TSTAMP}/${IAM}
  qstats.sh ${QSTATS_PARAMETERS}
  logger -t ${IAM} -- "dump queue stats: end"
}

main() {
  prepOut
  # collect default partition (shared)
  dumpStats
  queueempty=$(squeue --noheader | wc -l)
  if [ "${queueempty}" -ne 0 ] ; then
    sleep 10
    date | tee -a ${LOGDIR}/${TSTAMP}/${IAM}
    main
  fi
}

main
exit 0
