.TH "vc/cfg/provision/bin/.provision.sh" 3 "Mon Mar 23 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vc/cfg/provision/bin/.provision.sh
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "Exported String \fBVERBOSE\fP = ${VERBOSE:\-''}"
.br
.ti -1c
.RI "Exported String \fBERREXIT_PRINT_CALL_STACK\fP = ${ERREXIT_PRINT_CALL_STACK:\-'true'}"
.br
.ti -1c
.RI "Exported String \fBHALT_PREREQ_ERROR\fP = ${HALT_PREREQ_ERROR:\-''}"
.br
.ti -1c
.RI "Exported String \fBHALT_ERREXIT\fP = ${HALT_ERREXIT:\-''}"
.br
.ti -1c
.RI "Exported String \fBHUSH_OUTPUT\fP = ${HUSH_OUTPUT:\-''}"
.br
.ti -1c
.RI "Exported String \fBPREVENT_SLASHVAGRANT_MOUNT\fP = ${PREVENT_SLASHVAGRANT_MOUNT:\-'true'}"
.br
.ti -1c
.RI "Exported String \fBPREFERRED_REPO\fP = ${PREFERRED_REPO:\-''}"
.br
.ti -1c
.RI "Exported String \fBONLY_REMOTE_REPOS\fP = ${ONLY_REMOTE_REPOS:\-''}"
.br
.ti -1c
.RI "Exported String \fBDEFAULT_PREFERRED_REPO\fP = 'rsync://linux\&.mirrors\&.es\&.net'"
.br
.ti -1c
.RI "Exported String \fBDEFAULT_COLUMNS\fP = 100"
.br
.ti -1c
.RI "Exported String \fBRSYNC_CENTOS_REPO\fP = ${RSYNC_CENTOS_REPO:\-''}"
.br
.ti -1c
.RI "Exported String \fBSKIP_SW\fP = ${SKIP_SW:\-''}"
.br
.ti -1c
.RI "Exported String \fBSKIP_UPDATERPMS\fP = ${SKIP_UPDATERPMS:\-''}"
.br
.ti -1c
.RI "Exported String \fBPREV_TIMESTAMP\fP = ''"
.br
.ti -1c
.RI "Exported String \fBIS_LANL_PINGABLE\fP = 'proxyout\&.lanl\&.gov'"
.br
.ti -1c
.RI "Exported String \fBLANL_PROXY\fP = ${\fBIS_LANL_PINGABLE\fP}:8080"
.br
.ti -1c
.RI "Exported String \fBDEFAULT_OUTPUT_PROTOCOL\fP = ${DEFAULT_OUTPUT_PROTOCOL:\-'stdout'}"
.br
.RI "see \fBLog()\fP, setebug, VerifyEnv "
.ti -1c
.RI "Exported String \fBOUTPUT_PROTOCOL\fP = ${\fBDEFAULT_OUTPUT_PROTOCOL\fP}"
.br
.ti -1c
.RI "Exported String \fBLEAVE_BREADCRUMB_PROCS\fP = ${LEAVE_BREADCRUMB_PROCS:\-'parent_signals_all'}"
.br
.ti -1c
.RI "Exported String \fBTIDYUP_FORCE\fP = 'ignore_LEAVE_BREADCRUMBS'"
.br
.RI "local, this is interpreted as a parameter "
.ti -1c
.RI "Exported String \fBTIDYUP_LOCK\fP = ''"
.br
.ti -1c
.RI "Exported String \fBRSYNC_RETRY_LIMIT\fP = '7'"
.br
.ti -1c
.RI "Exported String \fBPG_RETRY_LIMIT\fP = '7'"
.br
.ti -1c
.RI "Exported String \fBPG_DEPTH_LIMIT\fP = ${\fBPG_RETRY_LIMIT\fP}"
.br
.ti -1c
.RI "Exported String \fBPG_DEPTH\fP = ${PG_DEPTH:\-'0'}"
.br
.ti -1c
.RI "Exported String \fBPGID\fP = ${PGID:\-$(($(ps \-o pgid= \-p '$$')))}"
.br
.ti -1c
.RI "Exported String \fBLOG_TO_STDERR\fP = ${LOG_TO_STDERR:\-''}"
.br
.ti -1c
.RI "Exported String \fBTRAP_NOISY\fP = ${TRAP_NOISY:\-'true'}"
.br
.ti -1c
.RI "Exported String \fBDEBUG\fP = ${DEBUG:\-''}"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "Exported String DEBUG = ${DEBUG:\-''}"

.SS "Exported String DEFAULT_COLUMNS = 100"

.SS "Exported String DEFAULT_OUTPUT_PROTOCOL = ${DEFAULT_OUTPUT_PROTOCOL:\-'stdout'}"

.PP
see \fBLog()\fP, setebug, VerifyEnv 
.SS "Exported String DEFAULT_PREFERRED_REPO = 'rsync://linux\&.mirrors\&.es\&.net'"

.SS "Exported String ERREXIT_PRINT_CALL_STACK = ${ERREXIT_PRINT_CALL_STACK:\-'true'}"

.SS "Exported String HALT_ERREXIT = ${HALT_ERREXIT:\-''}"

.SS "Exported String HALT_PREREQ_ERROR = ${HALT_PREREQ_ERROR:\-''}"

.SS "Exported String HUSH_OUTPUT = ${HUSH_OUTPUT:\-''}"

.SS "Exported String IS_LANL_PINGABLE = 'proxyout\&.lanl\&.gov'"

.SS "Exported String LANL_PROXY = ${\fBIS_LANL_PINGABLE\fP}:8080"

.SS "Exported String LEAVE_BREADCRUMB_PROCS = ${LEAVE_BREADCRUMB_PROCS:\-'parent_signals_all'}"

.SS "Exported String LOG_TO_STDERR = ${LOG_TO_STDERR:\-''}"

.SS "Exported String ONLY_REMOTE_REPOS = ${ONLY_REMOTE_REPOS:\-''}"

.SS "Exported String OUTPUT_PROTOCOL = ${\fBDEFAULT_OUTPUT_PROTOCOL\fP}"

.SS "Exported String PG_DEPTH = ${PG_DEPTH:\-'0'}"

.SS "Exported String PG_DEPTH_LIMIT = ${\fBPG_RETRY_LIMIT\fP}"

.SS "Exported String PG_RETRY_LIMIT = '7'"

.SS "Exported String PGID = ${PGID:\-$(($(ps \-o pgid= \-p '$$')))}"

.SS "Exported String PREFERRED_REPO = ${PREFERRED_REPO:\-''}"

.SS "Exported String PREV_TIMESTAMP = ''"

.SS "Exported String PREVENT_SLASHVAGRANT_MOUNT = ${PREVENT_SLASHVAGRANT_MOUNT:\-'true'}"

.SS "Exported String RSYNC_CENTOS_REPO = ${RSYNC_CENTOS_REPO:\-''}"

.SS "Exported String RSYNC_RETRY_LIMIT = '7'"

.SS "Exported String SKIP_SW = ${SKIP_SW:\-''}"

.SS "Exported String SKIP_UPDATERPMS = ${SKIP_UPDATERPMS:\-''}"

.SS "Exported String TIDYUP_FORCE = 'ignore_LEAVE_BREADCRUMBS'"

.PP
local, this is interpreted as a parameter 
.PP
\fBSee also:\fP
.RS 4
\fBTidyUp()\fP so must be no spaces in the value 
.RE
.PP

.SS "Exported String TIDYUP_LOCK = ''"

.SS "Exported String TRAP_NOISY = ${TRAP_NOISY:\-'true'}"

.SS "Exported String VERBOSE = ${VERBOSE:\-''}"

.SH "Author"
.PP 
Generated automatically by Doxygen for HPC Collaboratory from the source code\&.
