.TH "vc/common/provision/lib/.requires.sh" 3 "Mon Mar 23 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vc/common/provision/lib/.requires.sh
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "Exported String \fBREQUIREMENT_RETRY_LIMIT\fP = 20"
.br
.RI "This library file defines parameters and functions to load and execute requirements and prerequisites\&. "
.ti -1c
.RI "Exported String \fBREQUIREMENT_RETRY_SLEEP\fP = 3"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "Exported String REQUIREMENT_RETRY_LIMIT = 20"

.PP
This library file defines parameters and functions to load and execute requirements and prerequisites\&. 
.PP
\fBSee also:\fP
.RS 4
WaitForPrerequisites() each test will be tried \fBREQUIREMENT_RETRY_LIMIT\fP with a pause of \fBREQUIREMENT_RETRY_SLEEP\fP seconds between them 
.RE
.PP

.SS "Exported String REQUIREMENT_RETRY_SLEEP = 3"

.SH "Author"
.PP 
Generated automatically by Doxygen for HPC Collaboratory from the source code\&.
