.TH "cfg/vcfs/config/nfs/.shload.sh" 3 "Wed Apr 15 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cfg/vcfs/config/nfs/.shload.sh
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "Exported String \fBPROVISION_SRC_D\fP = /vagrant/cfg/provision"
.br
.RI "This file loads the initial set of shell parameters, constants and functions into the context of the <software>/<function>/script\&. It is a predecessor to the common functions, so must explicitly specify a few parameters (PROVISION_SRC_D, EX_SOFTWARE) locally\&. "
.ti -1c
.RI "Exported String \fBPROVISION_SRC_LIB_D\fP = ${\fBPROVISION_SRC_D\fP}/lib"
.br
.ti -1c
.RI "Exported String \fBPROVISION_SRC_INC_D\fP = ${\fBPROVISION_SRC_D\fP}/inc"
.br
.ti -1c
.RI "Exported String \fBSH_HEADERS\fP = $(ls ${\fBPROVISION_SRC_INC_D\fP})"
.br
.ti -1c
.RI "Exported String \fBSH_LIBS\fP = $(ls ${\fBPROVISION_SRC_LIB_D\fP})"
.br
.ti -1c
.RI "Exported String \fBEX_SOFTWARE\fP = 70"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "Exported String EX_SOFTWARE = 70"

.SS "Exported String PROVISION_SRC_D = /vagrant/cfg/provision"

.PP
This file loads the initial set of shell parameters, constants and functions into the context of the <software>/<function>/script\&. It is a predecessor to the common functions, so must explicitly specify a few parameters (PROVISION_SRC_D, EX_SOFTWARE) locally\&. 
.SS "Exported String PROVISION_SRC_INC_D = ${\fBPROVISION_SRC_D\fP}/inc"

.SS "Exported String PROVISION_SRC_LIB_D = ${\fBPROVISION_SRC_D\fP}/lib"

.SS "Exported String SH_HEADERS = $(ls ${\fBPROVISION_SRC_INC_D\fP})"

.SS "Exported String SH_LIBS = $(ls ${\fBPROVISION_SRC_LIB_D\fP})"

.SH "Author"
.PP 
Generated automatically by Doxygen for HPC Collaboratory from the source code\&.
