.TH "vc/cfg/vclogin/config/slurm/1.slurm-files-permissions" 3 "Wed Jan 1 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vc/cfg/vclogin/config/slurm/1.slurm-files-permissions
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for HPC Collaboratory from the source code\&.
