.TH "vc/cfg/vcdb/config/mariadb/4.create-slurm_acct_db" 3 "Tue Feb 11 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vc/cfg/vcdb/config/mariadb/4.create-slurm_acct_db
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for HPC Collaboratory from the source code\&.
