.TH "cfg/vcdb/config/mariadb Directory Reference" 3 "Wed Apr 15 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cfg/vcdb/config/mariadb Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB1\&.mk\-dirs\-files\fP"
.br
.ti -1c
.RI "file \fB2\&.selinux\-chcon\fP"
.br
.ti -1c
.RI "file \fB3\&.service\-on\fP"
.br
.ti -1c
.RI "file \fB4\&.verify\-mysql\-config\fP"
.br
.ti -1c
.RI "file \fB5\&.create\-slurm_acct_db\fP"
.br
.ti -1c
.RI "file \fB6\&.grant\-db\-access\fP"
.br
.ti -1c
.RI "file \fBdirs\-setypes\fP"
.br
.ti -1c
.RI "file \fBRPMS\&.Manifest\fP"
.br
.ti -1c
.RI "file \fBsebool\fP"
.br
.in -1c
