.TH "vc/cfg/vc2/requires/vcsched Directory Reference" 3 "Mon Mar 23 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vc/cfg/vc2/requires/vcsched Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB1\&.ping\fP"
.br
.ti -1c
.RI "file \fB2\&.socket\-SLURMCTLD\fP"
.br
.ti -1c
.RI "file \fB3\&.slurm\-conf\fP"
.br
.ti -1c
.RI "file \fB4\&.provisioned\fP"
.br
.ti -1c
.RI "file \fBipaddr\fP"
.br
.in -1c
