.TH "cfg/vcgate/requires/vcfs Directory Reference" 3 "Wed Apr 15 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cfg/vcgate/requires/vcfs Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB\&.ipaddr\fP"
.br
.ti -1c
.RI "file \fB1\&.ping\fP"
.br
.ti -1c
.RI "file \fB2\&.socket\-NFS\fP"
.br
.ti -1c
.RI "file \fB3\&.rpc\-NFS\fP"
.br
.ti -1c
.RI "file \fB4\&.nfs\-mounts\fP"
.br
.ti -1c
.RI "file \fB5\&.nfs\-fs\-rwx\fP"
.br
.ti -1c
.RI "file \fB6\&.enable\-nfs\-local\-yum\-repo\fP"
.br
.ti -1c
.RI "file \fB7\&.provisioned\fP"
.br
.ti -1c
.RI "file \fBipaddr\fP"
.br
.in -1c
