.TH "vc/cfg/vcsched/verify/slurm Directory Reference" 3 "Mon Mar 23 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vc/cfg/vcsched/verify/slurm Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB1\&.slurm\-dbd\-commands\fP"
.br
.ti -1c
.RI "file \fB2\&.slurm\-ctld\-commands\fP"
.br
.ti -1c
.RI "file \fBrequired\&.services\fP"
.br
.in -1c
