.TH "vc/cfg/vcfs/config/nfs Directory Reference" 3 "Mon Mar 23 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vc/cfg/vcfs/config/nfs Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB\&.shload\&.sh\fP"
.br
.ti -1c
.RI "file \fB1\&.mark\-∕home∕vagrant∕common\fP"
.br
.ti -1c
.RI "file \fB2\&.create\-nfs\-exports\fP"
.br
.ti -1c
.RI "file \fBRPMS\&.Manifest\fP"
.br
.in -1c
