.TH "cfg/vc1/config/munge Directory Reference" 3 "Wed Apr 15 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cfg/vc1/config/munge Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB\&.RPMS\&.Manifest\fP"
.br
.ti -1c
.RI "file \fB1\&.munge\-files\-permissions\fP"
.br
.ti -1c
.RI "file \fB2\&.overlay\-munge\-service\fP"
.br
.ti -1c
.RI "file \fBRPMS\&.Manifest\fP"
.br
.in -1c
