.TH "vc/cfg/vcfs/config/firewall/zones/trusted Directory Reference" 3 "Mon Mar 23 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vc/cfg/vcfs/config/firewall/zones/trusted Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBadd\-port\fP"
.br
.ti -1c
.RI "directory \fBadd\-service\fP"
.br
.ti -1c
.RI "directory \fBinterfaces\fP"
.br
.in -1c
