.TH "cfg/vcbuild/config/slurm Directory Reference" 3 "Wed Apr 15 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cfg/vcbuild/config/slurm Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB1\&.slurm\-dirs\fP"
.br
.ti -1c
.RI "file \fB2\&.slurm\-files\-permissions\fP"
.br
.ti -1c
.RI "file \fB3\&.overlay\-slurm\-service\fP"
.br
.ti -1c
.RI "file \fB4\&.slurmd\fP"
.br
.ti -1c
.RI "file \fBrequired\&.service\fP"
.br
.in -1c
