.TH "cfg/vclogin/verify/slurm Directory Reference" 3 "Wed Apr 15 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cfg/vclogin/verify/slurm Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB1\&.daemon\-reload\fP"
.br
.ti -1c
.RI "file \fB2\&.dbd\-commands\fP"
.br
.ti -1c
.RI "file \fB3\&.ctld\-commands\fP"
.br
.ti -1c
.RI "file \fB4\&.nodes\-up\fP"
.br
.ti -1c
.RI "file \fB5\&.run\-test\-jobs\fP"
.br
.ti -1c
.RI "file \fBrequired\&.services\fP"
.br
.in -1c
