.TH "vc/cfg/vcdb/config/firewall/zones/trusted/add-port Directory Reference" 3 "Mon Mar 23 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vc/cfg/vcdb/config/firewall/zones/trusted/add-port Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB3306\fP"
.br
.ti -1c
.RI "file \fB6819\fP"
.br
.in -1c
