.TH "vc/cfg/vclogin/requires/vcdb Directory Reference" 3 "Mon Mar 23 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vc/cfg/vclogin/requires/vcdb Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB1\&.ping\fP"
.br
.ti -1c
.RI "file \fB2\&.socket\-SLURMDBD\fP"
.br
.ti -1c
.RI "file \fB3\&.provisioned\fP"
.br
.ti -1c
.RI "file \fBipaddr\fP"
.br
.in -1c
