.TH "cfg/provision/flag Directory Reference" 3 "Wed Apr 15 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cfg/provision/flag Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBNotes\fP"
.br
.ti -1c
.RI "file \fBPREFERRED_REPO\fP"
.br
.ti -1c
.RI "file \fBSKIP_SW\fP"
.br
.ti -1c
.RI "file \fBSKIP_UPDATERPMS\fP"
.br
.ti -1c
.RI "file \fBVERBOSE\fP"
.br
.in -1c
