.TH "vc/cfg/vcsvc/config/dnsmasq Directory Reference" 3 "Mon Mar 23 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vc/cfg/vcsvc/config/dnsmasq Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB\&.shload\&.sh\fP"
.br
.ti -1c
.RI "file \fB1\&.cp\-etc\-hosts\-to\-etc\-hosts~\fP"
.br
.ti -1c
.RI "file \fBRPMS\&.Manifest\fP"
.br
.in -1c
