.TH "common/provision Directory Reference" 3 "Wed Apr 15 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
common/provision Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBenv\fP"
.br
.ti -1c
.RI "directory \fBflag\fP"
.br
.ti -1c
.RI "directory \fBinc\fP"
.br
.ti -1c
.RI "directory \fBinstall\fP"
.br
.ti -1c
.RI "directory \fBlib\fP"
.br
.in -1c
