.TH "cfg/vclogin/requires Directory Reference" 3 "Wed Apr 15 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cfg/vclogin/requires Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBvc1\fP"
.br
.ti -1c
.RI "directory \fBvc2\fP"
.br
.ti -1c
.RI "directory \fBvcbuild\fP"
.br
.ti -1c
.RI "directory \fBvcdb\fP"
.br
.ti -1c
.RI "directory \fBvcfs\fP"
.br
.ti -1c
.RI "directory \fBvcsched\fP"
.br
.in -1c
