.TH "/home/sts/hpc-collab/bin Directory Reference" 3 "Wed Apr 15 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/sts/hpc-collab/bin Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcollectinvokinguserinfo\&.sh\fP"
.br
.ti -1c
.RI "file \fBcopyright\&.sh\fP"
.br
.ti -1c
.RI "file \fBdoxygen\-bash\&.sed\fP"
.br
.ti -1c
.RI "file \fBingestfromhost\&.sh\fP"
.br
.ti -1c
.RI "file \fBingestvagrantstate\&.sh\fP"
.br
.ti -1c
.RI "file \fBmarkprovisioned\&.sh\fP"
.br
.ti -1c
.RI "file \fBnodup\&.sh\fP"
.br
.ti -1c
.RI "file \fBprovision\&.sh\fP"
.br
.ti -1c
.RI "file \fBsavelogsdb\&.sh\fP"
.br
.ti -1c
.RI "file \fBsetpath\&.csh\fP"
.br
.ti -1c
.RI "file \fBsetpath\&.sh\fP"
.br
.ti -1c
.RI "file \fBunprovision\&.sh\fP"
.br
.ti -1c
.RI "file \fBverifylocalenv\&.sh\fP"
.br
.ti -1c
.RI "file \fBvg\fP"
.br
.in -1c
