.TH "vc/cfg/vcdb/config/slurm Directory Reference" 3 "Mon Mar 23 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vc/cfg/vcdb/config/slurm Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB2\&.start\-slurmdbd\-service\fP"
.br
.ti -1c
.RI "file \fB3\&.create\-cluster\-db\fP"
.br
.ti -1c
.RI "file \fB4\&.verify\-db\fP"
.br
.ti -1c
.RI "file \fB5\&.reconfigure\-munge\-file\-permissions\-for\-systemd\fP"
.br
.ti -1c
.RI "file \fBrequired\&.service\fP"
.br
.in -1c
