.TH "vc/cfg/vc2/config/vboxadd Directory Reference" 3 "Mon Mar 23 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vc/cfg/vc2/config/vboxadd Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB\&.RPMS\&.Manifest\fP"
.br
.ti -1c
.RI "file \fB1\&.need\-update\-vbox\-guest\-additions\fP"
.br
.ti -1c
.RI "file \fB2\&.install\-vbox\-prereq\-rpms\fP"
.br
.ti -1c
.RI "file \fB3\&.install\-vbox\-guest\-additions\fP"
.br
.ti -1c
.RI "file \fB4\&.vboxadd\-systemctl\-status\fP"
.br
.ti -1c
.RI "file \fBRPMS\&.Manifest\fP"
.br
.in -1c
