.TH "cfg/vcsched/config/firewall/zones/trusted/add-port Directory Reference" 3 "Wed Apr 15 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cfg/vcsched/config/firewall/zones/trusted/add-port Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB6817\fP"
.br
.in -1c
