.TH "vc/cfg/vclogin/config/slurm Directory Reference" 3 "Mon Mar 23 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vc/cfg/vclogin/config/slurm Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB1\&.mk\-slurm\-dirs\-slurmd\&.log\fP"
.br
.ti -1c
.RI "file \fB2\&.overlay\-slurm\-service\fP"
.br
.ti -1c
.RI "file \fB3\&.socket\-SLURMCTLD\fP"
.br
.ti -1c
.RI "file \fB3\&.socket\-SLURMDBD\fP"
.br
.ti -1c
.RI "file \fB4\&.configure\-slurm\-db\fP"
.br
.ti -1c
.RI "file \fB5\&.partitions\-up\fP"
.br
.ti -1c
.RI "file \fB6\&.slurmd\-service\-on\fP"
.br
.ti -1c
.RI "file \fB7\&.nodes\-up\fP"
.br
.ti -1c
.RI "file \fB8\&.restore\-munge\-file\-permissions\fP"
.br
.ti -1c
.RI "file \fBipaddr\-slurmctld\fP"
.br
.ti -1c
.RI "file \fBipaddr\-slurmdbd\fP"
.br
.ti -1c
.RI "file \fBrequired\&.service\fP"
.br
.in -1c
