.TH "common/provision/inc/cfgfs.h.sh" 3 "Wed Apr 15 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
common/provision/inc/cfgfs.h.sh
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "Exported String \fBHOMEVAGRANT\fP = /home/vagrant"
.br
.RI "This header file defines common names and hierarchy of the configuration file system layout\&. "
.ti -1c
.RI "Exported String \fBCOMMON\fP = ${\fBHOMEVAGRANT\fP}/common"
.br
.ti -1c
.RI "Exported String \fBHOME_BASEDIR\fP = ${\fBCOMMON\fP}/home"
.br
.ti -1c
.RI "Exported String \fBCFG_HOMEVAGRANT\fP = ${\fBHOMEVAGRANT\fP}/cfg"
.br
.ti -1c
.RI "Exported String \fBPROVISION_HOMEVAGRANT\fP = ${\fBCFG_HOMEVAGRANT\fP}/provision"
.br
.ti -1c
.RI "Exported String \fBCOMMON_REPOS\fP = ${\fBCOMMON\fP}/repos"
.br
.ti -1c
.RI "Exported String \fBLOCALREPO\fP = ${VAGRANT}/etc/localrepo"
.br
.ti -1c
.RI "Exported String \fBYUM_REPO_D\fP = /etc/yum\&.repos\&.d"
.br
.ti -1c
.RI "Exported String \fBLOCAL_REPO_ID\fP = local\-vcbuild"
.br
.ti -1c
.RI "Exported String \fBYUM_LOCALREPO_DEF\fP = ${\fBYUM_REPO_D\fP}/${\fBLOCAL_REPO_ID\fP}\&.repo"
.br
.ti -1c
.RI "Exported String \fBLOCALREPO_SUFFIX\fP = /centos/7/local"
.br
.ti -1c
.RI "Exported String \fBCOMMON_LOCALREPO\fP = ${\fBCOMMON_REPOS\fP}${\fBLOCALREPO_SUFFIX\fP}"
.br
.ti -1c
.RI "Exported String \fBCOMMON_PROVISION\fP = ${\fBCOMMON\fP}/provision"
.br
.ti -1c
.RI "Exported String \fBETC\fP = /etc"
.br
.ti -1c
.RI "Exported String \fBETCSLURM\fP = /etc/slurm"
.br
.ti -1c
.RI "Exported String \fBETCMUNGE\fP = /etc/munge"
.br
.ti -1c
.RI "Exported String \fBVC_COMMON\fP = ${\fBVC\fP}/common"
.br
.ti -1c
.RI "Exported String \fBCFG\fP = ${\fBVC\fP}/cfg"
.br
.ti -1c
.RI "Exported String \fBNODES\fP = $(echo $(ls ${\fBCFG\fP} | grep \-v provision))"
.br
.ti -1c
.RI "Exported String \fBXFR\fP = '${VC}/xfr'"
.br
.ti -1c
.RI "Exported String \fBISOS\fP = '${XFR}'"
.br
.ti -1c
.RI "Exported String \fBVAGRANTFILE\fP = ${\fBVC\fP}/Vagrantfile"
.br
.ti -1c
.RI "Exported String \fBROOT\fP = ${\fBCFG\fP}/${\fBHOSTNAME\fP}"
.br
.ti -1c
.RI "Exported String \fBSERVICES_D\fP = ${\fBROOT\fP}/services"
.br
.ti -1c
.RI "Exported String \fBSERVICES_ON\fP = ${\fBSERVICES_D\fP}/on"
.br
.ti -1c
.RI "Exported String \fBSERVICES_OFF\fP = ${\fBSERVICES_D\fP}/off"
.br
.ti -1c
.RI "Exported String \fBRPM\fP = ${\fBROOT\fP}/rpm"
.br
.ti -1c
.RI "Exported String \fBROOTFS\fP = ${\fBROOT\fP}/rootfs"
.br
.ti -1c
.RI "Exported String \fBREQUIREMENTS\fP = '${ROOT}/requires'"
.br
.ti -1c
.RI "Exported String \fBREPOS\fP = ${\fBCOMMON_REPOS\fP}"
.br
.ti -1c
.RI "Exported String \fBPROVISION_GENERIC\fP = ${\fBCFG\fP}/provision"
.br
.ti -1c
.RI "Exported String \fBFLAGS\fP = ${\fBPROVISION_GENERIC\fP}/flag"
.br
.ti -1c
.RI "Exported String \fBENV\fP = ${\fBPROVISION_GENERIC\fP}/env"
.br
.ti -1c
.RI "Exported String \fBUSERADD\fP = ${\fBCOMMON_PROVISION\fP}/useradd"
.br
.ti -1c
.RI "Exported String \fBUSERADD_PASSWD\fP = \&./passwd"
.br
.ti -1c
.RI "Exported String \fBUSERADD_PASSWD_CLEARTEXT\fP = ${\fBUSERADD_PASSWD\fP}/cleartext"
.br
.ti -1c
.RI "Exported String \fBUSERADD_PASSWD_ENCRYPTED\fP = ${\fBUSERADD_PASSWD\fP}/encrypted"
.br
.ti -1c
.RI "Exported String \fBSUDOERS_D\fP = 'sudoers\&.d'"
.br
.ti -1c
.RI "Exported String \fBETC_SUDOERS_D\fP = /etc/${\fBSUDOERS_D\fP}"
.br
.ti -1c
.RI "Exported String \fBMNT\fP = '/mnt'"
.br
.ti -1c
.RI "Exported String \fBTMP\fP = '/tmp'"
.br
.ti -1c
.RI "Exported String \fBBUILDWHAT\fP = build"
.br
.ti -1c
.RI "Exported String \fBINSTALLWHAT\fP = ${\fBCFG\fP}/${\fBHOSTNAME\fP}/install"
.br
.ti -1c
.RI "Exported String \fBCONFIGWHAT\fP = ${\fBCFG\fP}/${\fBHOSTNAME\fP}/config"
.br
.ti -1c
.RI "Exported String \fBVERIFYWHAT\fP = ${\fBCFG\fP}/${\fBHOSTNAME\fP}/verify"
.br
.ti -1c
.RI "Exported String \fBBUILDWHERE\fP = ${\fBHOMEVAGRANT\fP}/build"
.br
.ti -1c
.RI "Exported String \fBRPMS_ARCH\fP = rpmbuild/RPMS/${\fBARCH\fP}"
.br
.ti -1c
.RI "Exported String \fBRPMS_MANIFEST\fP = RPMS\&.Manifest"
.br
.ti -1c
.RI "Exported String \fBSTATE_D\fP = ${\fBVC_COMMON\fP}/\&._state"
.br
.ti -1c
.RI "Exported String \fBSTATE_RUNNING\fP = ${\fBSTATE_D\fP}/running"
.br
.ti -1c
.RI "Exported String \fBSTATE_PROVISIONED\fP = ${\fBSTATE_D\fP}/provisioned"
.br
.ti -1c
.RI "Exported String \fBSTATE_POWEROFF\fP = ${\fBSTATE_D\fP}/poweroff"
.br
.ti -1c
.RI "Exported String \fBSTATE_NONEXISTENT\fP = ${\fBSTATE_D\fP}/nonexistent"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "Exported String BUILDWHAT = build"

.SS "Exported String BUILDWHERE = ${\fBHOMEVAGRANT\fP}/build"

.SS "Exported String CFG = ${\fBVC\fP}/cfg"

.SS "Exported String CFG_HOMEVAGRANT = ${\fBHOMEVAGRANT\fP}/cfg"

.SS "Exported String COMMON = ${\fBHOMEVAGRANT\fP}/common"

.SS "Exported String COMMON_LOCALREPO = ${\fBCOMMON_REPOS\fP}${\fBLOCALREPO_SUFFIX\fP}"

.SS "Exported String COMMON_PROVISION = ${\fBCOMMON\fP}/provision"

.SS "Exported String COMMON_REPOS = ${\fBCOMMON\fP}/repos"

.SS "Exported String CONFIGWHAT = ${\fBCFG\fP}/${\fBHOSTNAME\fP}/config"

.SS "Exported String ENV = ${\fBPROVISION_GENERIC\fP}/env"

.SS "Exported String ETC = /etc"

.SS "Exported String ETC_SUDOERS_D = /etc/${\fBSUDOERS_D\fP}"

.SS "Exported String ETCMUNGE = /etc/munge"

.SS "Exported String ETCSLURM = /etc/slurm"

.SS "Exported String FLAGS = ${\fBPROVISION_GENERIC\fP}/flag"

.SS "Exported String HOME_BASEDIR = ${\fBCOMMON\fP}/home"

.SS "Exported String HOMEVAGRANT = /home/vagrant"

.PP
This header file defines common names and hierarchy of the configuration file system layout\&. 
.SS "Exported String INSTALLWHAT = ${\fBCFG\fP}/${\fBHOSTNAME\fP}/install"

.SS "Exported String ISOS = '${XFR}'"

.SS "Exported String LOCAL_REPO_ID = local\-vcbuild"

.SS "Exported String LOCALREPO = ${VAGRANT}/etc/localrepo"

.SS "Exported String LOCALREPO_SUFFIX = /centos/7/local"

.SS "Exported String MNT = '/mnt'"

.SS "Exported String NODES = $(echo $(ls ${\fBCFG\fP} | grep \-v provision))"

.SS "Exported String PROVISION_GENERIC = ${\fBCFG\fP}/provision"

.SS "Exported String PROVISION_HOMEVAGRANT = ${\fBCFG_HOMEVAGRANT\fP}/provision"

.SS "Exported String REPOS = ${\fBCOMMON_REPOS\fP}"

.SS "Exported String REQUIREMENTS = '${ROOT}/requires'"

.SS "Exported String ROOT = ${\fBCFG\fP}/${\fBHOSTNAME\fP}"

.SS "Exported String ROOTFS = ${\fBROOT\fP}/rootfs"

.SS "Exported String RPM = ${\fBROOT\fP}/rpm"

.SS "Exported String RPMS_ARCH = rpmbuild/RPMS/${\fBARCH\fP}"

.SS "Exported String RPMS_MANIFEST = RPMS\&.Manifest"

.SS "Exported String SERVICES_D = ${\fBROOT\fP}/services"

.SS "Exported String SERVICES_OFF = ${\fBSERVICES_D\fP}/off"

.SS "Exported String SERVICES_ON = ${\fBSERVICES_D\fP}/on"

.SS "Exported String STATE_D = ${\fBVC_COMMON\fP}/\&._state"

.SS "Exported String STATE_NONEXISTENT = ${\fBSTATE_D\fP}/nonexistent"

.SS "Exported String STATE_POWEROFF = ${\fBSTATE_D\fP}/poweroff"

.SS "Exported String STATE_PROVISIONED = ${\fBSTATE_D\fP}/provisioned"

.SS "Exported String STATE_RUNNING = ${\fBSTATE_D\fP}/running"

.SS "Exported String SUDOERS_D = 'sudoers\&.d'"

.SS "Exported String TMP = '/tmp'"

.SS "Exported String USERADD = ${\fBCOMMON_PROVISION\fP}/useradd"

.SS "Exported String USERADD_PASSWD = \&./passwd"

.SS "Exported String USERADD_PASSWD_CLEARTEXT = ${\fBUSERADD_PASSWD\fP}/cleartext"

.SS "Exported String USERADD_PASSWD_ENCRYPTED = ${\fBUSERADD_PASSWD\fP}/encrypted"

.SS "Exported String VAGRANTFILE = ${\fBVC\fP}/Vagrantfile"

.SS "Exported String VC_COMMON = ${\fBVC\fP}/common"

.SS "Exported String VERIFYWHAT = ${\fBCFG\fP}/${\fBHOSTNAME\fP}/verify"

.SS "Exported String XFR = '${VC}/xfr'"

.SS "Exported String YUM_LOCALREPO_DEF = ${\fBYUM_REPO_D\fP}/${\fBLOCAL_REPO_ID\fP}\&.repo"

.SS "Exported String YUM_REPO_D = /etc/yum\&.repos\&.d"

.SH "Author"
.PP 
Generated automatically by Doxygen for HPC Collaboratory from the source code\&.
