.TH "/home/sts/hpc-collab/bin/collectinvokinguserinfo.sh" 3 "Wed Apr 15 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/sts/hpc-collab/bin/collectinvokinguserinfo.sh
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "Exported String \fBVC\fP = ${VC:\-_VC_UNSET_}"
.br
.RI "This ANCHOR is used because the shell loader may be called from multiple locations: "
.ti -1c
.RI "Exported String \fBANCHOR\fP = $(dirname $0)/\&.\&./clusters/${\fBVC\fP}/cfg/provision"
.br
.ti -1c
.RI "Exported String \fBLOADER_SHLOAD\fP = ${\fBANCHOR\fP}/loader/shload\&.sh"
.br
.ti -1c
.RI "Exported String \fBBASEDIR\fP = ${\fBANCHOR\fP}/\&.\&./\&.\&."
.br
.ti -1c
.RI "Exported String \fBSUFFIX\fP = ${2:\-''}"
.br
.ti -1c
.RI "Exported String \fBCOMMON\fP = ${\fBBASEDIR\fP}/common"
.br
.ti -1c
.RI "Exported String \fBCOMMON_HOME\fP = ${\fBCOMMON\fP}/home"
.br
.ti -1c
.RI "Exported String \fBCOMMON_PROVISION\fP = ${\fBCOMMON\fP}/provision"
.br
.ti -1c
.RI "Exported String \fBCOMMON_USERADD\fP = ${\fBCOMMON_PROVISION\fP}/useradd"
.br
.ti -1c
.RI "Exported String \fBID\fP = $(id \-n \-u)"
.br
.ti -1c
.RI "Exported String \fBHOME\fP = ${HOME:\-/tmp}"
.br
.ti -1c
.RI "Exported String \fBSITE_VARS\fP = ${\fBENV\fP}/site\-vars\&.sh"
.br
.ti -1c
.RI "Exported String \fBUSER_HOME_DIR_SECONTEXT\fP = 'unconfined_u:object_r:user_home_dir_t:s0'"
.br
.ti -1c
.RI "Exported String \fBCONSTRUCT_USERADD_DIRS\fP = 'gid groups passwd secontext shell slurm sudoers\&.d uid'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "Exported String ANCHOR = $(dirname $0)/\&.\&./clusters/${\fBVC\fP}/cfg/provision"

.SS "Exported String BASEDIR = ${\fBANCHOR\fP}/\&.\&./\&.\&."

.SS "Exported String COMMON = ${\fBBASEDIR\fP}/common"

.SS "Exported String COMMON_HOME = ${\fBCOMMON\fP}/home"

.SS "Exported String COMMON_PROVISION = ${\fBCOMMON\fP}/provision"

.SS "Exported String COMMON_USERADD = ${\fBCOMMON_PROVISION\fP}/useradd"

.SS "Exported String CONSTRUCT_USERADD_DIRS = 'gid groups passwd secontext shell slurm sudoers\&.d uid'"

.SS "Exported String HOME = ${HOME:\-/tmp}"

.SS "Exported String ID = $(id \-n \-u)"

.SS "Exported String LOADER_SHLOAD = ${\fBANCHOR\fP}/loader/shload\&.sh"

.SS "Exported String SITE_VARS = ${\fBENV\fP}/site\-vars\&.sh"

.SS "Exported String SUFFIX = ${2:\-''}"

.SS "Exported String USER_HOME_DIR_SECONTEXT = 'unconfined_u:object_r:user_home_dir_t:s0'"

.SS "Exported String VC = ${VC:\-_VC_UNSET_}"

.PP
This ANCHOR is used because the shell loader may be called from multiple locations: 
.SH "Author"
.PP 
Generated automatically by Doxygen for HPC Collaboratory from the source code\&.
