.TH "vc/common/provision/lib/configfw.sh" 3 "Fri Jan 10 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vc/common/provision/lib/configfw.sh
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBConfigFW\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "Exported String \fBCONFIG_FIREWALL\fP = ${\fBCFG_HOMEVAGRANT\fP}/${\fBHOSTNAME\fP}/config/firewall"
.br
.RI "This library file contain the firewall configuration function(s)\&. "
.ti -1c
.RI "Exported String \fBFIREWALL_ROOT\fP = ${\fBCONFIG_FIREWALL\fP}"
.br
.ti -1c
.RI "Exported String \fBFIREWALL_ZONES\fP = ${\fBFIREWALL_ROOT\fP}/zones"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "ConfigFW ()"

.SH "Variable Documentation"
.PP 
.SS "Exported String CONFIG_FIREWALL = ${\fBCFG_HOMEVAGRANT\fP}/${\fBHOSTNAME\fP}/config/firewall"

.PP
This library file contain the firewall configuration function(s)\&. 
.SS "Exported String FIREWALL_ROOT = ${\fBCONFIG_FIREWALL\fP}"

.SS "Exported String FIREWALL_ZONES = ${\fBFIREWALL_ROOT\fP}/zones"

.SH "Author"
.PP 
Generated automatically by Doxygen for HPC Collaboratory from the source code\&.
