.TH "common/provision/lib/copyright.sh" 3 "Wed Apr 15 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
common/provision/lib/copyright.sh
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBCopyright\fP ()"
.br
.RI "This library file contains a function to emit the copyright notice\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "Copyright ()"

.PP
This library file contains a function to emit the copyright notice\&. so as to comply with the rules of the copyright notice\&. 
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for HPC Collaboratory from the source code\&.
