.TH "common/provision/inc/dynamic.h.sh" 3 "Wed Apr 15 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
common/provision/inc/dynamic.h.sh
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "Exported String \fBARCH\fP = $(uname \-m)"
.br
.RI "This header file sets initial values for dynamic run-time parameters\&. "
.ti -1c
.RI "Exported String \fBHOSTNAME\fP = $(hostname \-s)"
.br
.ti -1c
.RI "Exported String \fBIAM\fP = $(basename $0 \&.sh)"
.br
.ti -1c
.RI "Exported String \fBIAMFULL\fP = ${0}"
.br
.ti -1c
.RI "Exported String \fBORIGPWD\fP = $(pwd)"
.br
.ti -1c
.RI "Exported String \fBPGID\fP = ${PGID:\-$(($(ps \-o pgid= \-p '$$')))}"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "Exported String ARCH = $(uname \-m)"

.PP
This header file sets initial values for dynamic run-time parameters\&. 
.SS "Exported String HOSTNAME = $(hostname \-s)"

.SS "Exported String IAM = $(basename $0 \&.sh)"

.SS "Exported String IAMFULL = ${0}"

.SS "Exported String ORIGPWD = $(pwd)"

.SS "Exported String PGID = ${PGID:\-$(($(ps \-o pgid= \-p '$$')))}"

.SH "Author"
.PP 
Generated automatically by Doxygen for HPC Collaboratory from the source code\&.
