.TH "common/provision/inc/envparams.h.sh" 3 "Wed Apr 15 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
common/provision/inc/envparams.h.sh
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "Exported String \fBVERBOSE\fP = ${VERBOSE:\-''}"
.br
.RI "This header file contains global parameters which may be overridden by prior existence in the run-time environment\&. "
.ti -1c
.RI "Exported String \fBERREXIT_PRINT_CALL_STACK\fP = ${ERREXIT_PRINT_CALL_STACK:\-'true'}"
.br
.ti -1c
.RI "Exported String \fBHALT_PREREQ_ERROR\fP = ${HALT_PREREQ_ERROR:\-''}"
.br
.ti -1c
.RI "Exported String \fBHALT_ERREXIT\fP = ${HALT_ERREXIT:\-''}"
.br
.ti -1c
.RI "Exported String \fBHUSH_OUTPUT\fP = ${HUSH_OUTPUT:\-''}"
.br
.ti -1c
.RI "Exported String \fBPREVENT_SLASHVAGRANT_MOUNT\fP = ${PREVENT_SLASHVAGRANT_MOUNT:\-'true'}"
.br
.ti -1c
.RI "Exported String \fBPREFERRED_REPO\fP = ${PREFERRED_REPO:\-''}"
.br
.RI "XXX validity check that PREFERRED_REPO is an actual URL, else use DEFAULT_PREFERRED_REPO\&. "
.ti -1c
.RI "Exported String \fBONLY_REMOTE_REPOS\fP = ${ONLY_REMOTE_REPOS:\-''}"
.br
.ti -1c
.RI "Exported String \fBDEFAULT_PREFERRED_REPO\fP = 'rsync://linux\&.mirrors\&.es\&.net'"
.br
.ti -1c
.RI "Exported String \fBDEFAULT_COLUMNS\fP = ${COLUMNS:\-100}"
.br
.ti -1c
.RI "Exported String \fBRSYNC_CENTOS_REPO\fP = ${RSYNC_CENTOS_REPO:\-''}"
.br
.ti -1c
.RI "Exported String \fBSKIP_SW\fP = ${SKIP_SW:\-''}"
.br
.ti -1c
.RI "Exported String \fBSKIP_UPDATERPMS\fP = ${SKIP_UPDATERPMS:\-''}"
.br
.ti -1c
.RI "Exported String \fBIS_LANL_PINGABLE\fP = 'proxyout\&.lanl\&.gov'"
.br
.ti -1c
.RI "Exported String \fBLANL_PROXY\fP = ${\fBIS_LANL_PINGABLE\fP}:8080"
.br
.ti -1c
.RI "Exported String \fBIS_LANL\fP = ${IS_LANL:\-''}"
.br
.ti -1c
.RI "Exported String \fBDEFAULT_OUTPUT_PROTOCOL\fP = ${DEFAULT_OUTPUT_PROTOCOL:\-'stdout'}"
.br
.RI "see \fBLog()\fP, setebug, VerifyEnv, controls how error messages are emitted "
.ti -1c
.RI "Exported String \fBOUTPUT_PROTOCOL\fP = ${\fBDEFAULT_OUTPUT_PROTOCOL\fP}"
.br
.ti -1c
.RI "Exported String \fBLEAVE_BREADCRUMB_PROCS\fP = ${LEAVE_BREADCRUMB_PROCS:\-'parent_signals_all'}"
.br
.ti -1c
.RI "Exported String \fBTIDYUP_FORCE\fP = 'ignore_LEAVE_BREADCRUMBS'"
.br
.RI "local, this is interpreted as a parameter "
.ti -1c
.RI "Exported String \fBTIDYUP_LOCK\fP = ''"
.br
.ti -1c
.RI "Exported String \fBLOG_TO_STDERR\fP = ${LOG_TO_STDERR:\-''}"
.br
.ti -1c
.RI "Exported String \fBTRAP_NOISY\fP = ${TRAP_NOISY:\-'true'}"
.br
.ti -1c
.RI "Exported String \fBDEBUG\fP = ${DEBUG:\-''}"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "Exported String DEBUG = ${DEBUG:\-''}"
DEBUG chiefly governs the order of opreations, but perhaps should be subsumed into a level mechanism rather than a simple binary flag 
.SS "Exported String DEFAULT_COLUMNS = ${COLUMNS:\-100}"

.SS "Exported String DEFAULT_OUTPUT_PROTOCOL = ${DEFAULT_OUTPUT_PROTOCOL:\-'stdout'}"

.PP
see \fBLog()\fP, setebug, VerifyEnv, controls how error messages are emitted 
.SS "Exported String DEFAULT_PREFERRED_REPO = 'rsync://linux\&.mirrors\&.es\&.net'"

.SS "Exported String ERREXIT_PRINT_CALL_STACK = ${ERREXIT_PRINT_CALL_STACK:\-'true'}"

.SS "Exported String HALT_ERREXIT = ${HALT_ERREXIT:\-''}"

.SS "Exported String HALT_PREREQ_ERROR = ${HALT_PREREQ_ERROR:\-''}"

.SS "Exported String HUSH_OUTPUT = ${HUSH_OUTPUT:\-''}"

.SS "Exported String IS_LANL = ${IS_LANL:\-''}"

.SS "Exported String IS_LANL_PINGABLE = 'proxyout\&.lanl\&.gov'"

.SS "Exported String LANL_PROXY = ${\fBIS_LANL_PINGABLE\fP}:8080"

.SS "Exported String LEAVE_BREADCRUMB_PROCS = ${LEAVE_BREADCRUMB_PROCS:\-'parent_signals_all'}"

.SS "Exported String LOG_TO_STDERR = ${LOG_TO_STDERR:\-''}"

.SS "Exported String ONLY_REMOTE_REPOS = ${ONLY_REMOTE_REPOS:\-''}"

.SS "Exported String OUTPUT_PROTOCOL = ${\fBDEFAULT_OUTPUT_PROTOCOL\fP}"

.SS "Exported String PREFERRED_REPO = ${PREFERRED_REPO:\-''}"

.PP
XXX validity check that PREFERRED_REPO is an actual URL, else use DEFAULT_PREFERRED_REPO\&. 
.SS "Exported String PREVENT_SLASHVAGRANT_MOUNT = ${PREVENT_SLASHVAGRANT_MOUNT:\-'true'}"

.SS "Exported String RSYNC_CENTOS_REPO = ${RSYNC_CENTOS_REPO:\-''}"

.SS "Exported String SKIP_SW = ${SKIP_SW:\-''}"

.SS "Exported String SKIP_UPDATERPMS = ${SKIP_UPDATERPMS:\-''}"

.SS "Exported String TIDYUP_FORCE = 'ignore_LEAVE_BREADCRUMBS'"

.PP
local, this is interpreted as a parameter 
.PP
\fBSee also:\fP
.RS 4
\fBTidyUp()\fP so must be no spaces in the value 
.RE
.PP

.SS "Exported String TIDYUP_LOCK = ''"

.SS "Exported String TRAP_NOISY = ${TRAP_NOISY:\-'true'}"

.SS "Exported String VERBOSE = ${VERBOSE:\-''}"

.PP
This header file contains global parameters which may be overridden by prior existence in the run-time environment\&. 
.PP
\fBTodo\fP
.RS 4
consider moving some of these into associated function libraries 
.RE
.PP
parameters which govern provisioning execution behavior 
.SH "Author"
.PP 
Generated automatically by Doxygen for HPC Collaboratory from the source code\&.
