.TH "vc/cfg/provision/env/envvars.sh" 3 "Wed Jan 1 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vc/cfg/provision/env/envvars.sh
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "Exported String \fBLC_ALL\fP = en_US\&.UTF\-8"
.br
.ti -1c
.RI "Exported String \fBLANG\fP = en_US\&.UTF\-8"
.br
.ti -1c
.RI "Exported String \fBLANGUAGE\fP = en_US\&.UTF\-8"
.br
.ti -1c
.RI "Exported String \fBTZ\fP = MST7MDT"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "Exported String LANG = en_US\&.UTF\-8"

.SS "Exported String LANGUAGE = en_US\&.UTF\-8"

.SS "Exported String LC_ALL = en_US\&.UTF\-8"

.SS "Exported String TZ = MST7MDT"

.SH "Author"
.PP 
Generated automatically by Doxygen for HPC Collaboratory from the source code\&.
