.TH "common/provision/inc/exit.h.sh" 3 "Wed Apr 15 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
common/provision/inc/exit.h.sh
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "Exported String \fBEXIT_OK\fP = 0"
.br
.RI "This header file contains common exit codes by value and name\&. "
.ti -1c
.RI "Exported String \fBEX_OK\fP = ${\fBEXIT_OK\fP}"
.br
.ti -1c
.RI "Exported String \fBEX__BASE\fP = 64"
.br
.RI "the first error code in the common list of sysexits "
.ti -1c
.RI "Exported String \fBEX_USAGE\fP = 64"
.br
.RI "The command was used incorrectly\&. "
.ti -1c
.RI "Exported String \fBEX_DATAERR\fP = 65"
.br
.RI "The input data was incorrect\&. "
.ti -1c
.RI "Exported String \fBEX_NOINPUT\fP = 66"
.br
.RI "An input file did not exist or was unreadable\&. "
.ti -1c
.RI "Exported String \fBEX_NOUSER\fP = 67"
.br
.RI "The user specified did not exist\&. "
.ti -1c
.RI "Exported String \fBEX_NOHOST\fP = 68"
.br
.RI "The host specified did not exist\&. "
.ti -1c
.RI "Exported String \fBEX_UNAVAILABLE\fP = 69"
.br
.RI "A service is unavailable\&. "
.ti -1c
.RI "Exported String \fBEX_SOFTWARE\fP = 70"
.br
.RI "An internal software error has been detected\&. "
.ti -1c
.RI "Exported String \fBEX_OSERR\fP = 71"
.br
.RI "An operating system error has been detected\&. "
.ti -1c
.RI "Exported String \fBEX_OSFILE\fP = 72"
.br
.RI "Some system file does not exist or may not be accessed\&. "
.ti -1c
.RI "Exported String \fBEX_CANTCREAT\fP = 73"
.br
.RI "An output file cannot be created\&. "
.ti -1c
.RI "Exported String \fBEX_IOERR\fP = 74"
.br
.RI "An error occurred while doing I/O\&. "
.ti -1c
.RI "Exported String \fBEX_TEMPFAIL\fP = 75"
.br
.RI "A temporary failure occurred\&. Reattempts may succeed\&. "
.ti -1c
.RI "Exported String \fBEX_PROTOCOL\fP = 76"
.br
.RI "The remote system connection setup failed\&. "
.ti -1c
.RI "Exported String \fBEX_NOPERM\fP = 77"
.br
.RI "The user does not have authority to perform an action\&. "
.ti -1c
.RI "Exported String \fBEX_CONFIG\fP = 78"
.br
.RI "A configuration is missing or incorrect\&. "
.ti -1c
.RI "Exported String \fBEX__MAX\fP = 78"
.br
.RI "Maximum error code (not really) "
.ti -1c
.RI "Exported String \fBEX_ALREADY\fP = 114"
.br
.RI "Already mounted, already connected, already done\&. "
.ti -1c
.RI "Exported String \fBEX_SIGBASE\fP = 128"
.br
.RI "fatal signal exit = EX_SIGBASE+<signal-number> "
.ti -1c
.RI "String Array \fBExitCodeNames\fP"
.br
.RI "User (SysAdmin) courtesy: to emit the name of the exit code\&. "
.in -1c
.SH "Variable Documentation"
.PP 
.SS "Exported String EX__BASE = 64"

.PP
the first error code in the common list of sysexits 
.SS "Exported String EX__MAX = 78"

.PP
Maximum error code (not really) 
.SS "Exported String EX_ALREADY = 114"

.PP
Already mounted, already connected, already done\&. 
.SS "Exported String EX_CANTCREAT = 73"

.PP
An output file cannot be created\&. 
.SS "Exported String EX_CONFIG = 78"

.PP
A configuration is missing or incorrect\&. 
.SS "Exported String EX_DATAERR = 65"

.PP
The input data was incorrect\&. 
.SS "Exported String EX_IOERR = 74"

.PP
An error occurred while doing I/O\&. 
.SS "Exported String EX_NOHOST = 68"

.PP
The host specified did not exist\&. 
.SS "Exported String EX_NOINPUT = 66"

.PP
An input file did not exist or was unreadable\&. 
.SS "Exported String EX_NOPERM = 77"

.PP
The user does not have authority to perform an action\&. 
.SS "Exported String EX_NOUSER = 67"

.PP
The user specified did not exist\&. 
.SS "Exported String EX_OK = ${\fBEXIT_OK\fP}"

.SS "Exported String EX_OSERR = 71"

.PP
An operating system error has been detected\&. 
.SS "Exported String EX_OSFILE = 72"

.PP
Some system file does not exist or may not be accessed\&. 
.SS "Exported String EX_PROTOCOL = 76"

.PP
The remote system connection setup failed\&. 
.SS "Exported String EX_SIGBASE = 128"

.PP
fatal signal exit = EX_SIGBASE+<signal-number> 
.SS "Exported String EX_SOFTWARE = 70"

.PP
An internal software error has been detected\&. 
.SS "Exported String EX_TEMPFAIL = 75"

.PP
A temporary failure occurred\&. Reattempts may succeed\&. 
.SS "Exported String EX_UNAVAILABLE = 69"

.PP
A service is unavailable\&. 
.SS "Exported String EX_USAGE = 64"

.PP
The command was used incorrectly\&. 
.SS "Exported String EXIT_OK = 0"

.PP
This header file contains common exit codes by value and name\&. 
.PP
\fBSee also:\fP
.RS 4
Authoritative exit codes: \fC/usr/include/sysexits\&.h\fP 
.PP
Signals [Linux-specific]: \fC/usr/include/bits/signum\&.h\fP 
.PP
Errno's [Linux/ASM-specific]\fC/usr/include/asm-generic/errno\&.h\fP 
.PP
tldp\&.org et\&. al\&. for SIGBASE The operation worked, without error\&. 
.RE
.PP

.SS "String Array ExitCodeNames"

.PP
User (SysAdmin) courtesy: to emit the name of the exit code\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for HPC Collaboratory from the source code\&.
