.TH "vc/cfg/provision/bin/ingesthost.sh" 3 "Wed Jan 1 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vc/cfg/provision/bin/ingesthost.sh
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBSetFlags\fP ()"
.br
.ti -1c
.RI "\fBRc\fP (ecode, cmd, [msg])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "Exported String \fBPWD\fP = $(pwd)"
.br
.ti -1c
.RI "Exported String \fBIAM\fP = $(basename $0)"
.br
.ti -1c
.RI "Exported String \fBTIMEOUT\fP = 3"
.br
.ti -1c
.RI "Exported String \fBSILENT_CMD\fP = '>/dev/null 2>&1'"
.br
.ti -1c
.RI "Exported String \fBCFG\fP = vc/cfg"
.br
.ti -1c
.RI "Exported String \fBID\fP = $(id \-n \-u)"
.br
.ti -1c
.RI "Exported String \fBBASEDIR\fP = ${HOME}/vagrant/vc"
.br
.ti -1c
.RI "Exported String \fBCOMMON\fP = common"
.br
.ti -1c
.RI "Exported String \fBCOMMON_HOME_BASE\fP = ${\fBCOMMON\fP}/home"
.br
.ti -1c
.RI "Exported String \fBCOMMON_HOME\fP = ${\fBCOMMON_HOME_BASE\fP}/${\fBID\fP}"
.br
.ti -1c
.RI "Exported String \fBFLAGS\fP = ${\fBBASEDIR\fP}/${\fBCOMMON\fP}/provision/flag"
.br
.ti -1c
.RI "String AssociativeArray \fBExitCodeNames\fP"
.br
.RI "User (SysAdmin) courtesy: to emit the name of the exit code\&. "
.ti -1c
.RI "Exported String \fBEXIT_OK\fP = 0"
.br
.RI "The operation worked\&. "
.ti -1c
.RI "Exported String \fBEX_OK\fP = ${\fBEXIT_OK\fP}"
.br
.ti -1c
.RI "Exported String \fBEX__BASE\fP = 64"
.br
.RI "the first error code in the common list of sysexits "
.ti -1c
.RI "Exported String \fBEX_USAGE\fP = 64"
.br
.RI "The command was used incorrectly\&. "
.ti -1c
.RI "Exported String \fBEX_DATAERR\fP = 65"
.br
.RI "The input data was incorrect\&. "
.ti -1c
.RI "Exported String \fBEX_NOINPUT\fP = 66"
.br
.RI "An input file did not exist or was unreadable\&. "
.ti -1c
.RI "Exported String \fBEX_NOUSER\fP = 67"
.br
.RI "The user specified did not exist\&. "
.ti -1c
.RI "Exported String \fBEX_NOHOST\fP = 68"
.br
.RI "The host specified did not exist\&. "
.ti -1c
.RI "Exported String \fBEX_UNAVAILABLE\fP = 69"
.br
.RI "A service is unavailable\&. "
.ti -1c
.RI "Exported String \fBEX_SOFTWARE\fP = 70"
.br
.RI "An internal software error has been detected\&. "
.ti -1c
.RI "Exported String \fBEX_OSERR\fP = 71"
.br
.RI "An operating system error has been detected\&. "
.ti -1c
.RI "Exported String \fBEX_OSFILE\fP = 72"
.br
.RI "Some system file does not exist or may not be accessed\&. "
.ti -1c
.RI "Exported String \fBEX_CANTCREAT\fP = 73"
.br
.RI "An output file cannot be created\&. "
.ti -1c
.RI "Exported String \fBEX_IOERR\fP = 74"
.br
.RI "An error occurred while doing I/O\&. "
.ti -1c
.RI "Exported String \fBEX_TEMPFAIL\fP = 75"
.br
.RI "A temporary failure occurred\&. Reattempts may succeed\&. "
.ti -1c
.RI "Exported String \fBEX_PROTOCOL\fP = 76"
.br
.RI "The remote system connection setup failed\&. "
.ti -1c
.RI "Exported String \fBEX_NOPERM\fP = 77"
.br
.RI "The user does not have authority to perform an action\&. "
.ti -1c
.RI "Exported String \fBEX_CONFIG\fP = 78"
.br
.RI "A configuration is missing or incorrect\&. "
.ti -1c
.RI "Exported String \fBEX__MAX\fP = 78"
.br
.RI "Maximum error code (not really) "
.ti -1c
.RI "Exported String \fBEX_ALREADY\fP = 114"
.br
.RI "Already mounted, already connected, already done\&. "
.ti -1c
.RI "Exported String \fBEX_SIGBASE\fP = 128"
.br
.RI "fatal signal exit = EX_SIGBASE+<signal-number> "
.ti -1c
.RI "Exported String \fBSUFFIX\fP = ${2:\-''}"
.br
.ti -1c
.RI "Exported String \fBOUTPUT_PROTOCOL\fP = stdout"
.br
.ti -1c
.RI "Exported String \fBHALT_ERREXIT\fP = 'true'"
.br
.ti -1c
.RI "Exported String \fBDEFAULT_ORDER_OF_OPERATIONS\fP = ${DEBUG_DEFAULT_ORDER_OF_OPERATIONS}"
.br
.ti -1c
.RI "Exported String \fBTAR_CHECKPOINT_DEBUG_ARGS\fP = '\-\-checkpoint=1024 \-\-checkpoint\-action=dot'"
.br
.ti -1c
.RI "Exported String \fBHALT_PREREQ_ERROR\fP = 'true'"
.br
.ti -1c
.RI "Exported String \fBHUSH_OUTPUT\fP = 'true'"
.br
.ti -1c
.RI "Exported String \fBRSYNC_CENTOS_REPO\fP = ''"
.br
.ti -1c
.RI "Exported String \fBONLY_REMOTE_REPOS\fP = 'true'"
.br
.ti -1c
.RI "Exported String \fBPREFERRED_REPO\fP = $(cat ${\fBFLAGS\fP}/PREFERRED_REPO)"
.br
.ti -1c
.RI "Exported String \fBSKIP_SW\fP = $(cat ${\fBFLAGS\fP}/SKIP_SW)"
.br
.ti -1c
.RI "Exported String \fBSKIP_UPDATERPMS\fP = 'true'"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "Rc (ecode, cmd)"

.SS "SetFlags ()"

.SH "Variable Documentation"
.PP 
.SS "Exported String BASEDIR = ${HOME}/vagrant/vc"

.SS "Exported String CFG = vc/cfg"

.SS "Exported String COMMON = common"

.SS "Exported String COMMON_HOME = ${\fBCOMMON_HOME_BASE\fP}/${\fBID\fP}"

.SS "Exported String COMMON_HOME_BASE = ${\fBCOMMON\fP}/home"

.SS "Exported String DEFAULT_ORDER_OF_OPERATIONS = ${DEBUG_DEFAULT_ORDER_OF_OPERATIONS}"

.SS "Exported String EX__BASE = 64"

.PP
the first error code in the common list of sysexits 
.SS "Exported String EX__MAX = 78"

.PP
Maximum error code (not really) 
.SS "Exported String EX_ALREADY = 114"

.PP
Already mounted, already connected, already done\&. 
.SS "Exported String EX_CANTCREAT = 73"

.PP
An output file cannot be created\&. 
.SS "Exported String EX_CONFIG = 78"

.PP
A configuration is missing or incorrect\&. 
.SS "Exported String EX_DATAERR = 65"

.PP
The input data was incorrect\&. 
.SS "Exported String EX_IOERR = 74"

.PP
An error occurred while doing I/O\&. 
.SS "Exported String EX_NOHOST = 68"

.PP
The host specified did not exist\&. 
.SS "Exported String EX_NOINPUT = 66"

.PP
An input file did not exist or was unreadable\&. 
.SS "Exported String EX_NOPERM = 77"

.PP
The user does not have authority to perform an action\&. 
.SS "Exported String EX_NOUSER = 67"

.PP
The user specified did not exist\&. 
.SS "Exported String EX_OK = ${\fBEXIT_OK\fP}"

.SS "Exported String EX_OSERR = 71"

.PP
An operating system error has been detected\&. 
.SS "Exported String EX_OSFILE = 72"

.PP
Some system file does not exist or may not be accessed\&. 
.SS "Exported String EX_PROTOCOL = 76"

.PP
The remote system connection setup failed\&. 
.SS "Exported String EX_SIGBASE = 128"

.PP
fatal signal exit = EX_SIGBASE+<signal-number> 
.SS "Exported String EX_SOFTWARE = 70"

.PP
An internal software error has been detected\&. 
.SS "Exported String EX_TEMPFAIL = 75"

.PP
A temporary failure occurred\&. Reattempts may succeed\&. 
.SS "Exported String EX_UNAVAILABLE = 69"

.PP
A service is unavailable\&. 
.SS "Exported String EX_USAGE = 64"

.PP
The command was used incorrectly\&. 
.SS "Exported String EXIT_OK = 0"

.PP
The operation worked\&. 
.SS "String AssociativeArray ExitCodeNames"

.PP
User (SysAdmin) courtesy: to emit the name of the exit code\&. 
.PP
\fBSee also:\fP
.RS 4
Authoritative exit codes: \fC/usr/include/sysexits\&.h\fP 
.PP
Signals [Linux-specific]: \fC/usr/include/bits/signum\&.h\fP 
.PP
Errno's [Linux/ASM-specific]\fC/usr/include/asm-generic/errno\&.h\fP 
.PP
tldp\&.org et\&. al\&. for SIGBASE 
.RE
.PP

.SS "Exported String FLAGS = ${\fBBASEDIR\fP}/${\fBCOMMON\fP}/provision/flag"

.SS "Exported String HALT_ERREXIT = 'true'"

.SS "Exported String HALT_PREREQ_ERROR = 'true'"

.SS "Exported String HUSH_OUTPUT = 'true'"

.SS "Exported String IAM = $(basename $0)"

.SS "Exported String ID = $(id \-n \-u)"

.SS "Exported String ONLY_REMOTE_REPOS = 'true'"

.SS "Exported String OUTPUT_PROTOCOL = stdout"

.SS "Exported String PREFERRED_REPO = $(cat ${\fBFLAGS\fP}/PREFERRED_REPO)"

.SS "Exported String PWD = $(pwd)"

.SS "Exported String RSYNC_CENTOS_REPO = ''"

.SS "Exported String SILENT_CMD = '>/dev/null 2>&1'"

.SS "Exported String SKIP_SW = $(cat ${\fBFLAGS\fP}/SKIP_SW)"

.SS "Exported String SKIP_UPDATERPMS = 'true'"

.SS "Exported String SUFFIX = ${2:\-''}"

.SS "Exported String TAR_CHECKPOINT_DEBUG_ARGS = '\-\-checkpoint=1024 \-\-checkpoint\-action=dot'"

.SS "Exported String TIMEOUT = 3"

.SH "Author"
.PP 
Generated automatically by Doxygen for HPC Collaboratory from the source code\&.
