.TH "/home/sts/hpc-collab/bin/provision.sh" 3 "Wed Apr 15 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/sts/hpc-collab/bin/provision.sh
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "Exported String \fBPROVISION_SRC_D\fP = /${\fBBASEDIR\fP}/cfg/provision"
.br
.RI "This file contains the main driver for the provisioning functions and libraries\&. "
.ti -1c
.RI "Exported String \fBPROVISION_SRC_LIB_D\fP = ${\fBPROVISION_SRC_D\fP}/lib"
.br
.ti -1c
.RI "Exported String \fBPROVISION_SRC_INC_D\fP = ${\fBPROVISION_SRC_D\fP}/inc"
.br
.ti -1c
.RI "Exported String \fBPROVISION_SRC_ENV_D\fP = ${\fBPROVISION_SRC_D\fP}/env"
.br
.ti -1c
.RI "Exported String \fBEX_SOFTWARE\fP = 70"
.br
.ti -1c
.RI "Exported String \fBEX_OK\fP = 0"
.br
.ti -1c
.RI "Exported String \fBBASEDIR\fP = vagrant"
.br
.ti -1c
.RI "Exported String \fBSH_HEADERS\fP = $(ls ${\fBPROVISION_SRC_INC_D\fP})"
.br
.ti -1c
.RI "Exported String \fBSH_ENV\fP = $(ls ${\fBPROVISION_SRC_ENV_D\fP})"
.br
.ti -1c
.RI "Exported String \fBSH_LIBS\fP = $(ls ${\fBPROVISION_SRC_LIB_D\fP})"
.br
.ti -1c
.RI "Exported String \fBCORE_ORDER_OF_OPERATIONS\fP"
.br
.RI "This defines the provisioning order of operations\&. In some cases, especially those requiring custom configuration, it may be appropriate to rearrange the provisioning order of operations\&. "
.in -1c
.SH "Variable Documentation"
.PP 
.SS "Exported String BASEDIR = vagrant"

.SS "Exported String CORE_ORDER_OF_OPERATIONS"

.PP
This defines the provisioning order of operations\&. In some cases, especially those requiring custom configuration, it may be appropriate to rearrange the provisioning order of operations\&. 
.SS "Exported String EX_OK = 0"

.SS "Exported String EX_SOFTWARE = 70"

.SS "Exported String PROVISION_SRC_D = /${\fBBASEDIR\fP}/cfg/provision"

.PP
This file contains the main driver for the provisioning functions and libraries\&. The following cannot be in a sub-function in order for source <___> to have global scope, ex\&. EX_OK, etc\&. 
.SS "Exported String PROVISION_SRC_ENV_D = ${\fBPROVISION_SRC_D\fP}/env"

.SS "Exported String PROVISION_SRC_INC_D = ${\fBPROVISION_SRC_D\fP}/inc"

.SS "Exported String PROVISION_SRC_LIB_D = ${\fBPROVISION_SRC_D\fP}/lib"

.SS "Exported String SH_ENV = $(ls ${\fBPROVISION_SRC_ENV_D\fP})"

.SS "Exported String SH_HEADERS = $(ls ${\fBPROVISION_SRC_INC_D\fP})"

.SS "Exported String SH_LIBS = $(ls ${\fBPROVISION_SRC_LIB_D\fP})"

.SH "Author"
.PP 
Generated automatically by Doxygen for HPC Collaboratory from the source code\&.
