.TH "common/provision/inc/rc.h.sh" 3 "Wed Apr 15 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
common/provision/inc/rc.h.sh
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "Exported String \fBDEFAULT_TIMEOUT\fP = 1"
.br
.RI "This header file contains manifest constants for \fBRc()\fP and related routines\&. "
.ti -1c
.RI "Exported String \fBTIMEOUT\fP = ${\fBDEFAULT_TIMEOUT\fP}"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "Exported String DEFAULT_TIMEOUT = 1"

.PP
This header file contains manifest constants for \fBRc()\fP and related routines\&. 
.SS "Exported String TIMEOUT = ${\fBDEFAULT_TIMEOUT\fP}"

.SH "Author"
.PP 
Generated automatically by Doxygen for HPC Collaboratory from the source code\&.
