.TH "common/provision/lib/rc.sh" 3 "Wed Apr 15 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
common/provision/lib/rc.sh
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBRc\fP (ecode, cmd, [msg])"
.br
.RI "This library file contains a the commonly called routine to run an executable command\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "Rc (ecode, cmd)"

.PP
This library file contains a the commonly called routine to run an executable command\&. Rc (RunCommand) dispatches a command, tests its return code and ErrFunc()'s (ErrExits/Logs) as appropriate\&. It is typically called as: Rc ErrFunction ErrCode Cmd Msg where EX_OK is the exit code that indicates success of the command ErrFunction is what is called with the ErrCode and the output from the executing Cmd and Msg is passed to ErrFunction to emit on error\&. The return code from the Cmd is appended to the Msg when passed to ErrFunction\&. If ErrFunction returns, then this function's return code is the value collected from Cmd ErrFunction is expected to resemble \fBErrExit()\fP, \fBLog()\fP or in-job equivalents to them\&. 
.PP
\fBParameters:\fP
.RS 4
\fIefunc\fP 
.br
\fIecode\fP 
.br
\fIcmd\fP 
.br
\fI[msg]\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
if efunc() returns, the return code from the executed cmd 
.RE
.PP
\fBTodo\fP
.RS 4
extensions: embed 1) 'su - user' 2) allow 'ignore (all) return codes'
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for HPC Collaboratory from the source code\&.
