.TH "common/provision/inc/returncodes.h.sh" 3 "Wed Apr 15 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
common/provision/inc/returncodes.h.sh
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "Exported String \fBGREP_FOUND\fP = 0"
.br
.RI "This header file contains return codes for external utilities linkage\&. "
.ti -1c
.RI "Exported String \fBGREP_NOTFOUND\fP = 1"
.br
.ti -1c
.RI "Exported String \fBGREP_ERROR\fP = 2"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "Exported String GREP_ERROR = 2"

.SS "Exported String GREP_FOUND = 0"

.PP
This header file contains return codes for external utilities linkage\&. 
.SS "Exported String GREP_NOTFOUND = 1"

.SH "Author"
.PP 
Generated automatically by Doxygen for HPC Collaboratory from the source code\&.
