.TH "/home/sts/hpc-collab/bin/savelogsdb.sh" 3 "Wed Apr 15 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/sts/hpc-collab/bin/savelogsdb.sh
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "Exported String \fBVC\fP = ${VC:\-_VC_UNSET_}"
.br
.RI "This ANCHOR is used because the shell loader may be called from the primary host ('dom0') or from the guest host ('/vagrant/\&.\&.\&.') "
.ti -1c
.RI "Exported String \fBANCHOR\fP = $(dirname $0)/\&.\&./clusters/${\fBVC\fP}/cfg/provision"
.br
.ti -1c
.RI "Exported String \fBLOADER_SHLOAD\fP = ${\fBANCHOR\fP}/loader/shload\&.sh"
.br
.ti -1c
.RI "Exported String \fBBASEDIR\fP = ${\fBANCHOR\fP}/\&.\&./\&.\&."
.br
.ti -1c
.RI "Exported String \fBPWD\fP = $(pwd)"
.br
.ti -1c
.RI "Exported String \fBID\fP = $(id \-n \-u)"
.br
.ti -1c
.RI "Exported String \fBIAM\fP = $(basename $0 \&.sh)"
.br
.ti -1c
.RI "Exported String \fBTSTAMP\fP = $(date +%Y\&.%m\&.%d\&.%H%M)"
.br
.ti -1c
.RI "Exported String \fBREQUESTED_HOST\fP = ${1\-''}"
.br
.ti -1c
.RI "Exported String \fBVARLOG\fP = /var/log"
.br
.ti -1c
.RI "Exported String \fBTMPDIR\fP = ${TMPDIR:\-/tmp/${\fBIAM\fP}\&.${\fBTSTAMP\fP}\&.d}"
.br
.ti -1c
.RI "Exported String \fBSTORAGE_HOST\fP = ''"
.br
.ti -1c
.RI "Exported String \fBDB_HOST\fP = ''"
.br
.ti -1c
.RI "Exported String \fBSSH_OPTARGS\fP = '\-o StrictHostKeyChecking=no \-o UserKnownHostsFile=/dev/null'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "Exported String ANCHOR = $(dirname $0)/\&.\&./clusters/${\fBVC\fP}/cfg/provision"

.SS "Exported String BASEDIR = ${\fBANCHOR\fP}/\&.\&./\&.\&."

.SS "Exported String DB_HOST = ''"

.SS "Exported String IAM = $(basename $0 \&.sh)"

.SS "Exported String ID = $(id \-n \-u)"

.SS "Exported String LOADER_SHLOAD = ${\fBANCHOR\fP}/loader/shload\&.sh"

.SS "Exported String PWD = $(pwd)"

.SS "Exported String REQUESTED_HOST = ${1\-''}"

.SS "Exported String SSH_OPTARGS = '\-o StrictHostKeyChecking=no \-o UserKnownHostsFile=/dev/null'"

.SS "Exported String STORAGE_HOST = ''"

.SS "Exported String TMPDIR = ${TMPDIR:\-/tmp/${\fBIAM\fP}\&.${\fBTSTAMP\fP}\&.d}"

.SS "Exported String TSTAMP = $(date +%Y\&.%m\&.%d\&.%H%M)"

.SS "Exported String VARLOG = /var/log"

.SS "Exported String VC = ${VC:\-_VC_UNSET_}"

.PP
This ANCHOR is used because the shell loader may be called from the primary host ('dom0') or from the guest host ('/vagrant/\&.\&.\&.') 
.SH "Author"
.PP 
Generated automatically by Doxygen for HPC Collaboratory from the source code\&.
