.TH "cfg/provision/env/site-vars.sh" 3 "Wed Apr 15 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cfg/provision/env/site-vars.sh
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "Exported String \fBLANG\fP = ${LANL:\-en_US\&.UTF\-8}"
.br
.ti -1c
.RI "Exported String \fBLANGUAGE\fP = ${LANGUAGE:\-${\fBLANG\fP}}"
.br
.ti -1c
.RI "Exported String \fBLC_ALL\fP = ${LC_ALL:\-${\fBLANG\fP}}"
.br
.ti -1c
.RI "Exported String \fBTZ\fP = ${TZ:\-MST7MDT}"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "Exported String LANG = ${LANL:\-en_US\&.UTF\-8}"

.SS "Exported String LANGUAGE = ${LANGUAGE:\-${\fBLANG\fP}}"

.SS "Exported String LC_ALL = ${LC_ALL:\-${\fBLANG\fP}}"

.SS "Exported String TZ = ${TZ:\-MST7MDT}"

.SH "Author"
.PP 
Generated automatically by Doxygen for HPC Collaboratory from the source code\&.
