.TH "common/provision/inc/slurmparams.h.sh" 3 "Wed Apr 15 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
common/provision/inc/slurmparams.h.sh
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "Exported String \fBSLURMCONF\fP = ${\fBCOMMON\fP}/${\fBETCSLURM\fP}/slurm\&.conf"
.br
.RI "This header file defines commonly used slurm-related parameters\&. "
.ti -1c
.RI "Exported String \fBSLURMDBDCONF\fP = ${\fBCOMMON\fP}/${\fBETCSLURM\fP}/slurmdbd\&.conf"
.br
.ti -1c
.RI "Exported String \fBDEFAULT_CTLDPORT_LOWER\fP = 6817"
.br
.ti -1c
.RI "Exported String \fBDEFAULT_CTLDPORT_UPPER\fP = 6817"
.br
.ti -1c
.RI "Exported String \fBDEFAULT_CTLDPORT\fP = ${\fBDEFAULT_CTLDPORT_LOWER\fP}"
.br
.ti -1c
.RI "Exported String \fBDEFAULT_SLURMDPORT\fP = 6818"
.br
.ti -1c
.RI "Exported String \fBDEFAULT_DBDPORT\fP = 6819"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "Exported String DEFAULT_CTLDPORT = ${\fBDEFAULT_CTLDPORT_LOWER\fP}"

.SS "Exported String DEFAULT_CTLDPORT_LOWER = 6817"

.SS "Exported String DEFAULT_CTLDPORT_UPPER = 6817"

.SS "Exported String DEFAULT_DBDPORT = 6819"

.SS "Exported String DEFAULT_SLURMDPORT = 6818"

.SS "Exported String SLURMCONF = ${\fBCOMMON\fP}/${\fBETCSLURM\fP}/slurm\&.conf"

.PP
This header file defines commonly used slurm-related parameters\&. 
.SS "Exported String SLURMDBDCONF = ${\fBCOMMON\fP}/${\fBETCSLURM\fP}/slurmdbd\&.conf"

.SH "Author"
.PP 
Generated automatically by Doxygen for HPC Collaboratory from the source code\&.
