.TH "todo" 3 "Wed Apr 15 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBMember \fBRc\fP (ecode, cmd, [msg])\fP" 1c
extensions: embed 1) 'su - user' 2) allow 'ignore (all) return codes'
.PP
.IP "\fBMember \fBTrapCleanup\fP (TRAP_NOISY, DEBUG)\fP" 1c
return (SIGBASE + <signal number>) when != EX_OK  
.IP "\fBMember \fBVERBOSE\fP \fP" 1c
consider moving some of these into associated function libraries 
.PP

