.TH "/home/sts/hpc-collab/bin/unprovision.sh" 3 "Wed Apr 15 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/sts/hpc-collab/bin/unprovision.sh
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBClearVagrantfileSyncFolderDisabled\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "Exported String \fBVC\fP = ${VC:\-_UNSET_VC_}"
.br
.RI "remove 'provisioned' flag file for this node, disable the automatic /vagrant mount in Vagrantfile "
.ti -1c
.RI "Exported String \fBANCHOR\fP = $(dirname $0)/\&.\&./clusters/${\fBVC\fP}/cfg/provision"
.br
.ti -1c
.RI "Exported String \fBLOADER_SHLOAD\fP = ${\fBANCHOR\fP}/loader/shload\&.sh"
.br
.ti -1c
.RI "Exported String \fBBASEDIR\fP = ${\fBANCHOR\fP}/\&.\&./\&.\&."
.br
.ti -1c
.RI "Exported String \fBSUFFIX\fP = ${2:\-''}"
.br
.ti -1c
.RI "Exported String \fBPWD\fP = $(pwd)"
.br
.ti -1c
.RI "Exported String \fBVC_COMMON\fP = ${\fBVC\fP}/common"
.br
.ti -1c
.RI "Exported String \fBVAGRANTFILE\fP = ${\fBVC\fP}/Vagrantfile"
.br
.ti -1c
.RI "Exported String \fBHOSTNAME\fP = $(hostname \-s)"
.br
.ti -1c
.RI "Exported String \fBSTATE_D\fP = ${\fBVC_COMMON\fP}/\&._state"
.br
.ti -1c
.RI "Exported String \fBPROVISIONED\fP = ${\fBSTATE_D\fP}/provisioned"
.br
.ti -1c
.RI "Exported String \fBREQUESTED_HOST\fP = ${1:\-${\fBHOSTNAME\fP}}"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "ClearVagrantfileSyncFolderDisabled ()"

.SH "Variable Documentation"
.PP 
.SS "Exported String ANCHOR = $(dirname $0)/\&.\&./clusters/${\fBVC\fP}/cfg/provision"

.SS "Exported String BASEDIR = ${\fBANCHOR\fP}/\&.\&./\&.\&."

.SS "Exported String HOSTNAME = $(hostname \-s)"

.SS "Exported String LOADER_SHLOAD = ${\fBANCHOR\fP}/loader/shload\&.sh"

.SS "Exported String PROVISIONED = ${\fBSTATE_D\fP}/provisioned"

.SS "Exported String PWD = $(pwd)"

.SS "Exported String REQUESTED_HOST = ${1:\-${\fBHOSTNAME\fP}}"

.SS "Exported String STATE_D = ${\fBVC_COMMON\fP}/\&._state"

.SS "Exported String SUFFIX = ${2:\-''}"

.SS "Exported String VAGRANTFILE = ${\fBVC\fP}/Vagrantfile"

.SS "Exported String VC = ${VC:\-_UNSET_VC_}"

.PP
remove 'provisioned' flag file for this node, disable the automatic /vagrant mount in Vagrantfile This ANCHOR is used because the shell loader may be called from the primary host ('dom0') or from the guest host ('/vagrant/\&.\&.\&.') 
.SS "Exported String VC_COMMON = ${\fBVC\fP}/common"

.SH "Author"
.PP 
Generated automatically by Doxygen for HPC Collaboratory from the source code\&.
