.TH "common/provision/lib/verbosewarnlog.sh" 3 "Wed Apr 15 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
common/provision/lib/verbosewarnlog.sh
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBLog\fP (BASHPID, \fBIAM\fP, \fBLOG_TO_STDERR\fP)"
.br
.RI "This library file contains routines that emit messages\&. "
.ti -1c
.RI "\fBVerbose\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "Exported String \fBCOLUMNS\fP = ${columns}"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "Log (BASHPID, \fBIAM\fP, \fBLOG_TO_STDERR\fP)"

.PP
This library file contains routines that emit messages\&. emit a message to to stderr & syslog 
.PP
\fBParameters:\fP
.RS 4
\fIErrorMessage\fP 
.br
\fIBASHPID\fP 
.br
\fIIAM\fP 
.br
\fILOG_TO_STDERR\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "Verbose ()"

.SH "Variable Documentation"
.PP 
.SS "Exported String COLUMNS = ${columns}"

.SH "Author"
.PP 
Generated automatically by Doxygen for HPC Collaboratory from the source code\&.
