.TH "/home/sts/hpc-collab/bin/verifylocalenv.sh" 3 "Wed Apr 15 2020" "HPC Collaboratory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/sts/hpc-collab/bin/verifylocalenv.sh
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "Exported String \fBVC\fP = ${VC:\-_VC_UNSET_}"
.br
.RI "This ANCHOR is used because the shell loader may be called from the primary host ('dom0') or from the guest host ('/vagrant/\&.\&.\&.') "
.ti -1c
.RI "Exported String \fBANCHOR\fP = cfg/provision"
.br
.ti -1c
.RI "Exported String \fBLOADER_SHLOAD\fP = ${\fBANCHOR\fP}/loader/shload\&.sh"
.br
.ti -1c
.RI "Exported String \fBSUFFIX\fP = ${2:\-''}"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "Exported String ANCHOR = cfg/provision"

.SS "Exported String LOADER_SHLOAD = ${\fBANCHOR\fP}/loader/shload\&.sh"

.SS "Exported String SUFFIX = ${2:\-''}"

.SS "Exported String VC = ${VC:\-_VC_UNSET_}"

.PP
This ANCHOR is used because the shell loader may be called from the primary host ('dom0') or from the guest host ('/vagrant/\&.\&.\&.') 
.SH "Author"
.PP 
Generated automatically by Doxygen for HPC Collaboratory from the source code\&.
