#!/bin/bash

set -o pipefail
set -o nounset

export PATH=${PATH}:../bin

LOGDIR=../logs
TSTAMP=$(date +%y%m%d.%H%M)
PWD=$(pwd)
IAM=$(basename ${PWD})
JOBNAME=${IAM}-
TSTAMP=$(date +%y%m%d.%H%M)
TIMEOUT=1

QSTATS_PARAMETERS="-V -c -b -B -P -R"
QSTATS_STDOUT_PARAMETERS="-D ${QSTATS_PARAMETERS}"

prepOut() {
  mkdir -p ${LOGDIR}/${TSTAMP}
  touch "${LOGDIR}/${TSTAMP}/${IAM}"
  return
}

dumpStats() {
  logger -t ${IAM} -- "dump queue stats: begin" </dev/null
  echo "Output: ${LOGDIR}/${TSTAMP}/${IAM}"
  qstats.sh ${QSTATS_STDOUT_PARAMETERS} | tee ${LOGDIR}/${TSTAMP}/${IAM}
  qstats.sh ${QSTATS_PARAMETERS}
  logger -t ${IAM} -- "dump queue stats: end" </dev/null
  return
}

ensureIdle() {
	local limit=90 #two-second cycles

  queueLength=$(squeue --format=%i --noheader | wc -l)
  while [ ${queueLength} -gt 0 ] ; 
  do
    if [ ${queueLength} -ne 0 ] ; then
      echo "Queue is not idle; queue length=${queueLength}, pausing: ${TIMEOUT}" | tee "${LOGDIR}/${TSTAMP}/${IAM}"
    fi
    sleep ${TIMEOUT}
    TIMEOUT=$(expr ${TIMEOUT} + ${TIMEOUT})
    queueLength=$(squeue --format=%i --noheader | wc -l)
  done
  return
}

main() {
  prepOut
  ensureIdle
  # collect default partition (shared)
  dumpStats
  #if a user is monitoring, give them a chance to review
  sleep ${TIMEOUT}
  return
}

main
exit 0

# vim: tabstop=2 shiftwidth=2 expandtab background=dark
