# -*- mode: ruby -*-
# vi: set ft=ruby tabstop=2 shiftwidth=2 syntax=on background=dark :

require 'pathname'

REPODISK_SIZE = 16	# Gb

clustername_fullpath_raw = %x[pwd]
clustername_fullpath     = "#{clustername_fullpath_raw}"
clustername_fullpath     = #{clustername_fullpath}.chomp
clustername              = Pathname.new(clustername_fullpath).basename
clustername              = "#{clustername}".chomp

ENV["LC_ALL"] = "en_US.UTF-8"
ENV["VC"]     = "#{clustername}"
ENV["TZ"]     = "MST7MDT"

### XXX nodes_file = "#{clustername_fullpath_raw}".chomp + "/Vagrantfile." + clustername + ".nodes"
### XXX nodes_file_path = Pathname.new(nodes_file)
### XXX if !File.exists?(nodes_file_path)
### XXX   print "nodes_file_path:#{nodes_file_path} does not exist\n"
### XXX   exit
### XXX end
### XXX load File.expand_path(nodes_file_path)

### XXX ### XXX ### XXX ###
### The ruby way is to define nodes in an external YAML file, rather than to define within ruby
### XXX for now, include it inline here, or explore a file tree walk to collect generically
### XXX including doesn't allow us to define the 'nodes' variables as included files have their own separate scope
### @todo find some ruby-correct way to use this file's scope so that the Vagrantfile could be a common templated version 

# -*- mode: ruby -*-
# vi: set ft=ruby tabstop=2 shiftwidth=2 syntax=on background=dark :

hosts  = "./common/etc/hosts"
ethers = "./common/etc/ethers"

ingestfromhost_vcfs_path = "./cfg/vcfs/attributes/ingestfromhost/path"
ingestfromhost_vcfs_args = "./cfg/vcfs/attributes/ingestfromhost/args"

nodes = {

  "vxsched" => {  :ip             => `grep ' vxsched ' #{hosts}  | awk '{printf "%s",$1}'`,
									:mac            => `grep ' vxsched ' #{ethers} | awk '{printf "%s",$1}' | sed 's/://g'`,
									:bridge         => nil,
									:memory         => %x[ls cfg/vxsched/attributes/memory],
									:cpus	          => %x[ls cfg/vxsched/attributes/procs],
									:ingestfromhost => nil,
									:adddiskpath    => nil
								},

  "vx1"			=> {  :ip	            => `grep ' vx1 ' #{hosts}  | awk '{printf "%s",$1}'`,
									:mac            => `grep ' vx1 ' #{ethers} | awk '{printf "%s",$1}' | sed 's/://g'`,
									:bridge         => nil,
									:memory         => %x[ls cfg/vx1/attributes/memory],
									:cpus           => %x[ls cfg/vx1/attributes/procs],
									:ingestfromhost => nil,
									:adddiskpath    => nil
								},

  "vx2"			=> {  :ip             => `grep ' vx2 ' #{hosts}  | awk '{printf "%s",$1}'`,
									:mac            => `grep ' vx2 ' #{ethers} | awk '{printf "%s",$1}' | sed 's/://g'`,
									:bridge         => nil,
									:memory         => %x[ls cfg/vx2/attributes/memory],
									:cpus           => %x[ls cfg/vx2/attributes/procs],
									:ingestfromhost => nil,
									:adddiskpath    => nil
								},

  "vxlogin"		=> {:ip             => `grep ' vxlogin ' #{hosts}  | awk '{printf "%s",$1}'`,
									:mac            => `grep ' vxlogin ' #{ethers} | awk '{printf "%s",$1}' | sed 's/://g'`,
									:bridge         => nil,
									:memory         => %x[ls cfg/vxlogin/attributes/memory],
									:cpus           => %x[ls cfg/vxlogin/attributes/procs],
									:ingestfromhost => nil,
									:adddiskpath    => nil
								}
}
###


### XXX ### XXX ### XXX ###


Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"

  config.ssh.forward_env   = ["TZ", "LC_ALL", "VC"]
  config.ssh.forward_agent = true
  config.ssh.forward_x11   = true

  config.vm.provision "shell", path:  "../common/bin/provision.sh"

  config.vm.synced_folder ".",                "/vagrant",                       create: true,
                            type: "nfs", nfs_udp: false, nfs_version: 4,
                            mount_options: [ 'rw', 'tcp', 'async', 'actimeo=3',
                                             'rsize=131072', 'wsize=131072' ],
                            linux__nfs_options: ['rw','no_subtree_check','all_squash','async' ]

  config.vm.synced_folder "../vc",            "/vc",                            create: true,
                            type: "nfs", nfs_udp: false, nfs_version: 4,
                            mount_options: [ 'rw', 'tcp', 'async', 'actimeo=3',
                                             'rsize=131072', 'wsize=131072' ],
                            linux__nfs_options: ['rw','no_subtree_check','all_squash','async' ]

  config.vm.synced_folder "../vx",            "/vx",                            create: true,
                            type: "nfs", nfs_udp: false, nfs_version: 4,
                            mount_options: [ 'rw', 'tcp', 'async', 'actimeo=3',
                                             'rsize=131072', 'wsize=131072' ],
                            linux__nfs_options: ['rw','no_subtree_check','all_squash','async' ]

  config.vm.synced_folder "../../tarballs",   "/vc/xfr",                        create: true,
                            type: "nfs", nfs_udp: false, nfs_version: 4,
                            mount_options: [ 'rw', 'tcp', 'async', 'actimeo=3',
                                             'rsize=131072', 'wsize=131072' ],
                            linux__nfs_options: ['rw','no_subtree_check','all_squash','async' ]

  config.vm.synced_folder "../../tarballs",   "/vx/xfr",                        create: true,
                            type: "nfs", nfs_udp: false, nfs_version: 4,
                            mount_options: [ "rw", 'tcp', 'async', 'actimeo=3',
                                             'rsize=131072', 'wsize=131072' ],
                            linux__nfs_options: ['rw','no_subtree_check','all_squash','async' ]

  # in-cluster tools
  config.vm.synced_folder "../common/bin",    "/vagrant/cfg/provision/bin",     create: true,
                            type: "nfs", nfs_udp: false, nfs_version: 4,
                            mount_options: [ "ro", 'tcp', 'async', 'actimeo=60',
                                             'rsize=131072' ],
                            linux__nfs_options: ['ro','no_subtree_check','all_squash','async' ]

  config.vm.synced_folder "../common/env",    "/vx/cfg/provision/env",     create: true,
                            type: "nfs", nfs_udp: false, nfs_version: 4,
                            mount_options: [ "ro", 'tcp', 'async', 'actimeo=60',
                                             'rsize=131072' ],
                            linux__nfs_options: ['ro','no_subtree_check','all_squash','async' ]

  config.vm.synced_folder "../common/flag",   "/vx/cfg/provision/flag",    create: true,
                            type: "nfs", nfs_udp: false, nfs_version: 4,
                            mount_options: [ "ro", 'tcp', 'async', 'actimeo=60',
                                             'rsize=131072' ],
                            linux__nfs_options: ['ro','no_subtree_check','all_squash','async' ]

  config.vm.synced_folder "../common/inc",    "/vx/cfg/provision/inc",     create: true,
                            type: "nfs", nfs_udp: false, nfs_version: 4,
                            mount_options: [ "ro", 'tcp', 'async', 'actimeo=60',
                                             'rsize=131072' ],
                            linux__nfs_options: ['ro','no_subtree_check','all_squash','async' ]

  config.vm.synced_folder "../common/lib",    "/vx/cfg/provision/lib",     create: true,
                            type: "nfs", nfs_udp: false, nfs_version: 4,
                            mount_options: [ "ro", 'tcp', 'async', 'actimeo=60',
                                             'rsize=131072' ],
                            linux__nfs_options: ['ro','no_subtree_check','all_squash','async' ]

  config.vm.synced_folder "../common/loader", "/vx/cfg/provision/loader",  create: true,
                            type: "nfs", nfs_udp: false, nfs_version: 4,
                            mount_options: [ "ro", 'tcp', 'async', 'actimeo=60',
                                             'rsize=131072' ],
                            linux__nfs_options: ['ro','no_subtree_check','all_squash','async' ]

# config.vm.network # eth0 will always be NAT (Vagrant requirement)

  nodes.each_with_index do |(hostnm,manifest), index|
    config.vm.define hostnm do |cfg|
      cfg.vm.provider :virtualbox do |vb, override|
        vb.memory = manifest[:memory].chomp
        vb.cpus = manifest[:cpus].chomp

        override.vm.hostname = hostnm
				override.vm.graceful_halt_timeout = 10
        override.vm.network "private_network", nic_type: "virtio",
															:ip => manifest[:ip],
															:mac => manifest[:mac]

        if manifest[:bridge] then
          override.vm.network "public_network",
															:ip => manifest[:ip],
															nic_type: "virtio",
															:bridge => manifest[:bridge]
        end # manifest[:bridge]

        override.trigger.before [:up] do |noduplicate|
          noduplicate.run = {path: "../common/bin/nodup.sh", args: hostnm }
        end # override.trigger.before[:up]

				if #{manifest[:ingestfromhost]}.chomp then
          override.trigger.before [:up] do |ingestfromhost|

### XXX FIXME
### XXX     manifest[:ingestfromhost].each do |key,value|
### XXX       print "       ", "#{key}  #{value}\n"
### XXX     end
### XXX Doesn't execute unless run method is set, but need to set path and args

            ingestfromhost.run = { path: "../common/bin/ingestfromhost.sh" , args: "vcfs :DOTFILES :DOTSSH" }
### XXX FIXME ingestfromhost.run = { path: manifest[:ingestfromhost[#{path}]], args: manifest[:ingestfromhost[#{:args}]] }

          end # override.trigger.before [:up]
				end # manifest[:ingestfromhost]

         if manifest[:adddiskpath] then
           unless File.exist?(manifest[:adddiskpath])
             vb.customize ['createhd', '--filename', manifest[:adddiskpath],
														'--variant', 'Fixed', '--size', REPODISK_SIZE * 1024]
           end # File.exit?(manifest[:adddiskpath])

           vb.customize ['storageattach', :id,  '--storagectl', 'IDE Controller', '--port', 1, '--device', 0,
  													'--type', 'hdd', '--medium', manifest[:adddiskpath]]
         end # manifest[:adddiskpath]

        override.trigger.before [:destroy] do |unprovision|
          unprovision.run = {path: "../common/bin/unprovision.sh", args: hostnm }
        end # override.trigger.before

      end # cfg.vm.provider
    end # config.vm
  end # nodes
end # configure
