var searchData=
[
  ['2_2ecopy_2dcommon_2droot_2dkeys',['2.copy-common-root-keys',['../vcbuild_2config_2ssh_22_8copy-common-root-keys.html',1,'(Global Namespace)'],['../vcsched_2config_2ssh_22_8copy-common-root-keys.html',1,'(Global Namespace)'],['../vc1_2config_2ssh_22_8copy-common-root-keys.html',1,'(Global Namespace)'],['../vc2_2config_2ssh_22_8copy-common-root-keys.html',1,'(Global Namespace)'],['../vclogin_2config_2ssh_22_8copy-common-root-keys.html',1,'(Global Namespace)']]],
  ['2_2ecreate_2dnfs_2dexports',['2.create-nfs-exports',['../2_8create-nfs-exports.html',1,'']]],
  ['2_2edbd_2dcommands',['2.dbd-commands',['../2_8dbd-commands.html',1,'']]],
  ['2_2egenerate_2droot_2dkeys',['2.generate-root-keys',['../2_8generate-root-keys.html',1,'']]],
  ['2_2einstall_2dvbox_2dprereq_2drpms',['2.install-vbox-prereq-rpms',['../vcfs_2config_2vboxadd_22_8install-vbox-prereq-rpms.html',1,'(Global Namespace)'],['../vcbuild_2config_2vboxadd_22_8install-vbox-prereq-rpms.html',1,'(Global Namespace)'],['../vcdb_2config_2vboxadd_22_8install-vbox-prereq-rpms.html',1,'(Global Namespace)'],['../vcsched_2config_2vboxadd_22_8install-vbox-prereq-rpms.html',1,'(Global Namespace)'],['../vc1_2config_2vboxadd_22_8install-vbox-prereq-rpms.html',1,'(Global Namespace)'],['../vc2_2config_2vboxadd_22_8install-vbox-prereq-rpms.html',1,'(Global Namespace)'],['../vclogin_2config_2vboxadd_22_8install-vbox-prereq-rpms.html',1,'(Global Namespace)']]],
  ['2_2emk_2dslurm_2ddirs',['2.mk-slurm-dirs',['../2_8mk-slurm-dirs.html',1,'']]],
  ['2_2emodify_2dslurm_2espec',['2.modify-slurm.spec',['../2_8modify-slurm_8spec.html',1,'']]],
  ['2_2eoverlay_2dmunge_2dservice',['2.overlay-munge-service',['../vcbuild_2config_2munge_22_8overlay-munge-service.html',1,'(Global Namespace)'],['../vcdb_2config_2munge_22_8overlay-munge-service.html',1,'(Global Namespace)'],['../vcsched_2config_2munge_22_8overlay-munge-service.html',1,'(Global Namespace)'],['../vc1_2config_2munge_22_8overlay-munge-service.html',1,'(Global Namespace)'],['../vc2_2config_2munge_22_8overlay-munge-service.html',1,'(Global Namespace)'],['../vclogin_2config_2munge_22_8overlay-munge-service.html',1,'(Global Namespace)']]],
  ['2_2eoverlay_2dslurm_2dservice',['2.overlay-slurm-service',['../2_8overlay-slurm-service.html',1,'']]],
  ['2_2eprovisioned',['2.provisioned',['../vcdb_2requires_2vcbuild_22_8provisioned.html',1,'(Global Namespace)'],['../vcsched_2requires_2vcbuild_22_8provisioned.html',1,'(Global Namespace)'],['../vc1_2requires_2vcbuild_22_8provisioned.html',1,'(Global Namespace)'],['../vc2_2requires_2vcbuild_22_8provisioned.html',1,'(Global Namespace)'],['../vcgate_2requires_2vclogin_22_8provisioned.html',1,'(Global Namespace)']]],
  ['2_2eselinux_2dchcon',['2.selinux-chcon',['../2_8selinux-chcon.html',1,'']]],
  ['2_2eslurm_2dctld_2dcommands',['2.slurm-ctld-commands',['../2_8slurm-ctld-commands.html',1,'']]],
  ['2_2eslurm_2dfiles_2dpermissions',['2.slurm-files-permissions',['../vcbuild_2config_2slurm_22_8slurm-files-permissions.html',1,'(Global Namespace)'],['../vc1_2config_2slurm_22_8slurm-files-permissions.html',1,'(Global Namespace)'],['../vc2_2config_2slurm_22_8slurm-files-permissions.html',1,'(Global Namespace)']]],
  ['2_2eslurm_2dmkdir_2dprereq_2ddirs',['2.slurm-mkdir-prereq-dirs',['../2_8slurm-mkdir-prereq-dirs.html',1,'']]],
  ['2_2esocket_2ddns',['2.socket-DNS',['../2_8socket-DNS.html',1,'']]],
  ['2_2esocket_2dnfs',['2.socket-NFS',['../vcbuild_2requires_2vcfs_22_8socket-NFS.html',1,'(Global Namespace)'],['../vcdb_2requires_2vcfs_22_8socket-NFS.html',1,'(Global Namespace)'],['../vcsched_2requires_2vcfs_22_8socket-NFS.html',1,'(Global Namespace)'],['../vc1_2requires_2vcfs_22_8socket-NFS.html',1,'(Global Namespace)'],['../vc2_2requires_2vcfs_22_8socket-NFS.html',1,'(Global Namespace)'],['../vclogin_2requires_2vcfs_22_8socket-NFS.html',1,'(Global Namespace)'],['../vcgate_2requires_2vcfs_22_8socket-NFS.html',1,'(Global Namespace)']]],
  ['2_2esocket_2dntp',['2.socket-NTP',['../2_8socket-NTP.html',1,'']]],
  ['2_2esocket_2dslurmctld',['2.socket-SLURMCTLD',['../vc1_2requires_2vcsched_22_8socket-SLURMCTLD.html',1,'(Global Namespace)'],['../vc2_2requires_2vcsched_22_8socket-SLURMCTLD.html',1,'(Global Namespace)'],['../vclogin_2requires_2vcsched_22_8socket-SLURMCTLD.html',1,'(Global Namespace)']]],
  ['2_2esocket_2dslurmd',['2.socket-SLURMD',['../vc1_22_8socket-SLURMD.html',1,'(Global Namespace)'],['../vc2_22_8socket-SLURMD.html',1,'(Global Namespace)'],['../vcbuild_22_8socket-SLURMD.html',1,'(Global Namespace)']]],
  ['2_2esocket_2dslurmdbd',['2.socket-SLURMDBD',['../vcsched_2requires_2vcdb_22_8socket-SLURMDBD.html',1,'(Global Namespace)'],['../vclogin_2requires_2vcdb_22_8socket-SLURMDBD.html',1,'(Global Namespace)']]],
  ['2_2esocket_2dsyslog',['2.socket-SYSLOG',['../2_8socket-SYSLOG.html',1,'']]],
  ['2_2estart_2dslurmdbd_2dservice',['2.start-slurmdbd-service',['../2_8start-slurmdbd-service.html',1,'']]],
  ['2_2etimedatectl',['2.timedatectl',['../2_8timedatectl.html',1,'']]],
  ['2049',['2049',['../2049.html',1,'']]]
];
